//! Per-user Linux and macOS service installation for the relay daemon.
//!
//! Authentication notes
//! --------------------
//! Device credentials are stored in the CLI state directory and work under a
//! service without extra setup (`wsmp login`).
//!
//! CLI-token auth and endpoint header secrets are *references* to environment
//! variable names (never raw secrets in config). User services do not inherit
//! an interactive shell environment, so those variables must be provided via a
//! private environment file:
//!
//!   `wsmp service env-sync`  — copy currently exported required vars into the
//!                              private service env file (mode 0600)
//!   `wsmp service env-path`  — print that file's path
//!
//! The installers reference the env file without embedding secret values:
//! systemd uses `EnvironmentFile=`; macOS uses a 0700 wrapper that sources it.
//! Secrets are never written into unit/plist files and never printed.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result};
use clap::Subcommand;

use crate::config::Config;
use crate::output;

#[cfg(target_os = "linux")]
const LINUX_UNIT: &str = "wsmp.service";
#[cfg(target_os = "macos")]
const MACOS_LABEL: &str = "com.flycockpit.wsmp";
const SERVICE_ENV_FILE_NAME: &str = "service.env";
#[cfg(target_os = "macos")]
const MACOS_WRAPPER_NAME: &str = "wsmp-service-run.sh";

#[derive(Debug, clap::Args)]
pub struct Args {
    #[command(subcommand)]
    command: CommandName,
}

#[derive(Debug, Subcommand)]
enum CommandName {
    /// Install, enable, and start the per-user relay service.
    Install,
    /// Stop, disable, and remove the per-user relay service.
    Uninstall,
    /// Print the per-user relay service status.
    Status,
    /// Copy required environment variables from this shell into the private service env file.
    EnvSync,
    /// Print the path of the private service environment file.
    EnvPath,
}

pub fn run(args: &Args) -> Result<()> {
    match &args.command {
        CommandName::Install => install(),
        CommandName::Uninstall => uninstall(),
        CommandName::Status => status(),
        CommandName::EnvSync => env_sync(),
        CommandName::EnvPath => env_path(),
    }
}

/// Path to the private env file loaded by the installed user service.
pub fn service_env_file() -> Result<PathBuf> {
    Ok(crate::paths::config_dir()?.join(SERVICE_ENV_FILE_NAME))
}

#[cfg(target_os = "linux")]
fn service_file() -> Result<PathBuf> {
    let base = std::env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| dirs::home_dir().map(|home| home.join(".config")))
        .context("could not determine the user config directory")?;
    Ok(base.join("systemd/user").join(LINUX_UNIT))
}

#[cfg(target_os = "macos")]
fn service_file() -> Result<PathBuf> {
    let home = dirs::home_dir().context("could not determine the user home directory")?;
    Ok(home
        .join("Library/LaunchAgents")
        .join(format!("{MACOS_LABEL}.plist")))
}

#[cfg(target_os = "macos")]
fn macos_wrapper_path() -> Result<PathBuf> {
    Ok(crate::paths::state_dir()?.join(MACOS_WRAPPER_NAME))
}

#[cfg(target_os = "macos")]
fn macos_log_dir() -> Result<PathBuf> {
    let home = dirs::home_dir().context("could not determine the user home directory")?;
    Ok(home.join("Library/Logs/ws-model-proxy"))
}

#[cfg(not(any(target_os = "linux", target_os = "macos")))]
fn service_file() -> Result<PathBuf> {
    anyhow::bail!("service installation is only supported on Linux and macOS")
}

fn executable() -> Result<String> {
    std::env::current_exe()
        .context("resolving the wsmp executable")?
        .into_os_string()
        .into_string()
        .map_err(|_| anyhow::anyhow!("wsmp executable path is not valid UTF-8"))
}

/// Env var names the relay may need at runtime (CLI token + endpoint headers).
pub fn required_service_env_names(config: &Config) -> Vec<String> {
    let mut names = Vec::new();
    if let Some(env) = &config.cli_token_env {
        names.push(env.clone());
    }
    for endpoint in &config.endpoints {
        for header in &endpoint.headers {
            if !names.iter().any(|existing| existing == &header.env) {
                names.push(header.env.clone());
            }
        }
    }
    names
}

/// Render a dotenv-style private env file body. Values are written as-is after
/// a basic safety check; callers must only pass validated env names.
pub fn format_service_env_file(entries: &[(String, String)]) -> Result<String> {
    let mut out = String::from(
        "# Private environment for the wsmp user service.\n\
         # Generated by `wsmp service env-sync`. Mode should be 0600.\n\
         # Do not commit this file. Device credentials do not need entries here.\n",
    );
    for (name, value) in entries {
        crate::config::validate_env_name(name)?;
        if value.as_bytes().contains(&b'\n') || value.as_bytes().contains(&b'\0') {
            anyhow::bail!(
                "environment variable `{name}` contains characters that cannot be stored in the service env file"
            );
        }
        // Quote values so spaces/shell metacharacters survive `set -a; . file`.
        out.push_str(name);
        out.push('=');
        out.push('"');
        for ch in value.chars() {
            match ch {
                '\\' => out.push_str("\\\\"),
                '"' => out.push_str("\\\""),
                '$' => out.push_str("\\$"),
                '`' => out.push_str("\\`"),
                _ => out.push(ch),
            }
        }
        out.push('"');
        out.push('\n');
    }
    Ok(out)
}

/// Quote a single ExecStart argument for a systemd unit.
pub fn systemd_quote_arg(value: &str) -> String {
    let safe = value.chars().all(|ch| {
        ch.is_ascii_alphanumeric() || matches!(ch, '/' | '.' | '_' | '-' | ':' | '@' | '+' | '=')
    });
    if safe {
        return value.to_string();
    }
    let mut out = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            // systemd treats `%` as a specifier in unit files.
            '%' => out.push_str("%%"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

/// Render a systemd user unit for the relay.
pub fn render_systemd_user_unit(executable: &str, env_file: &str) -> String {
    let exec = systemd_quote_arg(executable);
    let env_file = systemd_quote_arg(env_file);
    format!(
        "[Unit]\n\
         Description=WS Model Proxy relay\n\
         After=network-online.target\n\
         Wants=network-online.target\n\
         \n\
         [Service]\n\
         Type=simple\n\
         ExecStart={exec} daemon start --foreground\n\
         Restart=on-failure\n\
         RestartSec=5\n\
         # Optional: CLI-token / endpoint-header env vars (see `wsmp service env-sync`).\n\
         # The leading `-` means a missing file is not fatal (device credentials still work).\n\
         EnvironmentFile=-{env_file}\n\
         WorkingDirectory=%h\n\
         StandardOutput=journal\n\
         StandardError=journal\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n"
    )
}

/// Render a macOS LaunchAgent plist. `program` is the wrapper script path so the
/// plist never embeds secret environment values.
pub fn render_launch_agent_plist(
    label: &str,
    program: &str,
    working_directory: &str,
    stdout_path: &str,
    stderr_path: &str,
) -> String {
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n\
         <plist version=\"1.0\">\n\
         <dict>\n\
         \t<key>Label</key>\n\
         \t<string>{label}</string>\n\
         \t<key>ProgramArguments</key>\n\
         \t<array>\n\
         \t\t<string>{program}</string>\n\
         \t</array>\n\
         \t<key>RunAtLoad</key>\n\
         \t<true/>\n\
         \t<key>KeepAlive</key>\n\
         \t<true/>\n\
         \t<key>ThrottleInterval</key>\n\
         \t<integer>5</integer>\n\
         \t<key>ProcessType</key>\n\
         \t<string>Background</string>\n\
         \t<key>WorkingDirectory</key>\n\
         \t<string>{working_directory}</string>\n\
         \t<key>StandardOutPath</key>\n\
         \t<string>{stdout_path}</string>\n\
         \t<key>StandardErrorPath</key>\n\
         \t<string>{stderr_path}</string>\n\
         </dict>\n\
         </plist>\n",
        label = xml_escape(label),
        program = xml_escape(program),
        working_directory = xml_escape(working_directory),
        stdout_path = xml_escape(stdout_path),
        stderr_path = xml_escape(stderr_path),
    )
}

/// Render the 0700 wrapper that sources the private env file then execs wsmp.
pub fn render_macos_service_wrapper(executable: &str, env_file: &str) -> String {
    // Single-quoted shell paths: reject embedded single quotes rather than
    // inventing complex escaping for a generated path we control.
    format!(
        "#!/bin/sh\n\
         # Generated by `wsmp service install`. Sources the private env file\n\
         # (CLI-token / endpoint-header vars) without storing secrets in the plist.\n\
         set -eu\n\
         ENV_FILE='{env_file}'\n\
         if [ -f \"$ENV_FILE\" ]; then\n\
         \tset -a\n\
         \t# shellcheck disable=SC1090\n\
         \t. \"$ENV_FILE\"\n\
         \tset +a\n\
         fi\n\
         exec '{executable}' daemon start --foreground\n",
        env_file = shell_single_quote(env_file),
        executable = shell_single_quote(executable),
    )
}

fn shell_single_quote(value: &str) -> String {
    // Paths from current_exe / config_dir should not contain `'`; defend anyway.
    value.replace('\'', "'\"'\"'")
}

fn xml_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

#[cfg(target_os = "linux")]
fn install() -> Result<()> {
    let file = service_file()?;
    let executable = executable()?;
    let env_file = service_env_file()?;
    ensure_service_env_placeholder(&env_file)?;
    let unit = render_systemd_user_unit(&executable, &env_file.display().to_string());
    write_service_file(&file, &unit)?;
    run_command("systemctl", &["--user", "daemon-reload"])?;
    // enable --now is idempotent enough for reinstall/upgrade: unit path is
    // rewritten above, then reloaded and (re)started.
    run_command("systemctl", &["--user", "enable", "--now", LINUX_UNIT])?;
    // Restart so an already-running unit picks up a replaced binary/unit.
    let _ = Command::new("systemctl")
        .args(["--user", "restart", LINUX_UNIT])
        .status();
    print_install_notes(&env_file)?;
    output::line(format!("installed and started `{}`", file.display()))
}

#[cfg(target_os = "macos")]
fn install() -> Result<()> {
    let file = service_file()?;
    let executable = executable()?;
    let env_file = service_env_file()?;
    ensure_service_env_placeholder(&env_file)?;

    let wrapper = macos_wrapper_path()?;
    if let Some(parent) = wrapper.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating `{}`", parent.display()))?;
        set_private_dir(parent)?;
    }
    let wrapper_body = render_macos_service_wrapper(&executable, &env_file.display().to_string());
    write_private_script(&wrapper, wrapper_body.as_bytes())?;

    let log_dir = macos_log_dir()?;
    fs::create_dir_all(&log_dir).with_context(|| format!("creating `{}`", log_dir.display()))?;
    let home = dirs::home_dir().context("could not determine the user home directory")?;
    let stdout_path = log_dir.join("relay.out.log");
    let stderr_path = log_dir.join("relay.err.log");
    let plist = render_launch_agent_plist(
        MACOS_LABEL,
        &wrapper.display().to_string(),
        &home.display().to_string(),
        &stdout_path.display().to_string(),
        &stderr_path.display().to_string(),
    );
    write_service_file(&file, &plist)?;

    let domain = launchd_domain()?;
    // Upgrade/reinstall: boot out any previous registration, then bootstrap.
    let _ = Command::new("launchctl")
        .args(["bootout", &domain, &file.display().to_string()])
        .status();
    // Older macOS used unload; bootout is preferred on modern versions.
    let _ = Command::new("launchctl")
        .args(["unload", &file.display().to_string()])
        .status();
    run_command(
        "launchctl",
        &["bootstrap", &domain, &file.display().to_string()],
    )?;
    // kickstart forces a (re)start after bootstrap/reinstall.
    let _ = Command::new("launchctl")
        .args(["kickstart", "-k", &format!("{domain}/{MACOS_LABEL}")])
        .status();

    print_install_notes(&env_file)?;
    output::line(format!("installed and started `{}`", file.display()))
}

#[cfg(not(any(target_os = "linux", target_os = "macos")))]
fn install() -> Result<()> {
    let _ = service_file()?;
    unreachable!()
}

#[cfg(target_os = "linux")]
fn uninstall() -> Result<()> {
    let file = service_file()?;
    let _ = Command::new("systemctl")
        .args(["--user", "disable", "--now", LINUX_UNIT])
        .status();
    if file.exists() {
        fs::remove_file(&file).with_context(|| format!("removing `{}`", file.display()))?;
    }
    let _ = Command::new("systemctl")
        .args(["--user", "daemon-reload"])
        .status();
    output::line("uninstalled relay service")
}

#[cfg(target_os = "macos")]
fn uninstall() -> Result<()> {
    let file = service_file()?;
    let domain = launchd_domain()?;
    let _ = Command::new("launchctl")
        .args(["bootout", &domain, &file.display().to_string()])
        .status();
    let _ = Command::new("launchctl")
        .args(["unload", &file.display().to_string()])
        .status();
    if file.exists() {
        fs::remove_file(&file).with_context(|| format!("removing `{}`", file.display()))?;
    }
    if let Ok(wrapper) = macos_wrapper_path() {
        if wrapper.exists() {
            let _ = fs::remove_file(&wrapper);
        }
    }
    output::line("uninstalled relay service")
}

#[cfg(not(any(target_os = "linux", target_os = "macos")))]
fn uninstall() -> Result<()> {
    let _ = service_file()?;
    unreachable!()
}

#[cfg(target_os = "linux")]
fn status() -> Result<()> {
    run_command("systemctl", &["--user", "status", LINUX_UNIT])
}

#[cfg(target_os = "macos")]
fn status() -> Result<()> {
    let domain = launchd_domain()?;
    run_command("launchctl", &["print", &format!("{domain}/{MACOS_LABEL}")])
}

#[cfg(not(any(target_os = "linux", target_os = "macos")))]
fn status() -> Result<()> {
    let _ = service_file()?;
    unreachable!()
}

fn env_path() -> Result<()> {
    output::line(service_env_file()?.display().to_string())
}

fn env_sync() -> Result<()> {
    let config = Config::load()?;
    let names = required_service_env_names(&config);
    if names.is_empty() {
        output::line(
            "no CLI-token or endpoint-header environment variables are configured; \
             device credentials do not need a service env file",
        )?;
        return Ok(());
    }

    let mut entries = Vec::new();
    let mut missing = Vec::new();
    for name in &names {
        match std::env::var(name) {
            Ok(value) if !value.is_empty() => entries.push((name.clone(), value)),
            _ => missing.push(name.clone()),
        }
    }

    let path = service_env_file()?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating `{}`", parent.display()))?;
        set_private_dir(parent)?;
    }
    let body = format_service_env_file(&entries)?;
    write_private_file(&path, body.as_bytes())?;

    if entries.is_empty() {
        output::line(format!(
            "wrote empty service env file `{}` (none of the required variables were set in this shell)",
            path.display()
        ))?;
    } else {
        output::line(format!(
            "wrote {} environment variable(s) to `{}`",
            entries.len(),
            path.display()
        ))?;
        for (name, _) in &entries {
            output::line(format!("  synced `{name}`"))?;
        }
    }
    if !missing.is_empty() {
        output::line("missing from this shell (not written):")?;
        for name in missing {
            output::line(format!("  `{name}`"))?;
        }
        output::line(
            "export the missing variables, re-run `wsmp service env-sync`, then restart the service",
        )?;
    }
    Ok(())
}

fn ensure_service_env_placeholder(path: &Path) -> Result<()> {
    if path.exists() {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating `{}`", parent.display()))?;
        set_private_dir(parent)?;
    }
    let body = format_service_env_file(&[])?;
    write_private_file(path, body.as_bytes())
}

fn print_install_notes(env_file: &Path) -> Result<()> {
    output::line(format!(
        "service environment file: `{}` (mode 0600; never commit secrets)",
        env_file.display()
    ))?;
    output::line(
        "device login credentials are read from the CLI state directory and need no env file",
    )?;
    output::line(
        "if you use `wsmp token login <ENV>` or endpoint header env vars, run \
         `wsmp service env-sync` from a shell where those variables are exported, then restart the service",
    )?;
    #[cfg(target_os = "linux")]
    output::line(
        "tip: for a user service that survives logout, run `loginctl enable-linger \"$USER\"`",
    )?;
    Ok(())
}

fn write_service_file(file: &Path, contents: &str) -> Result<()> {
    let parent = file
        .parent()
        .context("service file has no parent directory")?;
    fs::create_dir_all(parent).with_context(|| format!("creating `{}`", parent.display()))?;
    fs::write(file, contents).with_context(|| format!("writing `{}`", file.display()))
}

fn write_private_file(path: &Path, bytes: &[u8]) -> Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        use std::os::unix::fs::PermissionsExt;

        let mut file = fs::OpenOptions::new()
            .create(true)
            .truncate(true)
            .write(true)
            .mode(0o600)
            .open(path)
            .with_context(|| format!("opening `{}`", path.display()))?;
        file.write_all(bytes)
            .with_context(|| format!("writing `{}`", path.display()))?;
        file.sync_all()
            .with_context(|| format!("syncing `{}`", path.display()))?;
        let mut permissions = file
            .metadata()
            .with_context(|| format!("reading metadata for `{}`", path.display()))?
            .permissions();
        permissions.set_mode(0o600);
        fs::set_permissions(path, permissions)
            .with_context(|| format!("setting private permissions on `{}`", path.display()))
    }
    #[cfg(not(unix))]
    {
        let mut file = fs::OpenOptions::new()
            .create(true)
            .truncate(true)
            .write(true)
            .open(path)
            .with_context(|| format!("opening `{}`", path.display()))?;
        file.write_all(bytes)
            .with_context(|| format!("writing `{}`", path.display()))?;
        file.sync_all()
            .with_context(|| format!("syncing `{}`", path.display()))
    }
}

#[cfg(target_os = "macos")]
fn write_private_script(path: &Path, bytes: &[u8]) -> Result<()> {
    write_private_file(path, bytes)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut permissions = fs::metadata(path)
            .with_context(|| format!("reading metadata for `{}`", path.display()))?
            .permissions();
        permissions.set_mode(0o700);
        fs::set_permissions(path, permissions)
            .with_context(|| format!("setting executable permissions on `{}`", path.display()))?;
    }
    Ok(())
}

#[cfg(unix)]
fn set_private_dir(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let metadata =
        fs::metadata(path).with_context(|| format!("reading metadata for `{}`", path.display()))?;
    let mut permissions = metadata.permissions();
    permissions.set_mode(0o700);
    fs::set_permissions(path, permissions)
        .with_context(|| format!("setting private permissions on `{}`", path.display()))
}

#[cfg(not(unix))]
fn set_private_dir(_path: &Path) -> Result<()> {
    Ok(())
}

fn run_command(program: &str, args: &[&str]) -> Result<()> {
    let status = Command::new(program)
        .args(args)
        .status()
        .with_context(|| format!("running `{program}`"))?;
    if status.success() {
        Ok(())
    } else {
        anyhow::bail!("`{program}` failed with {status}")
    }
}

#[cfg(target_os = "macos")]
fn launchd_domain() -> Result<String> {
    let output = Command::new("id")
        .arg("-u")
        .output()
        .context("determining the current user ID")?;
    if !output.status.success() {
        anyhow::bail!("`id -u` failed with {}", output.status);
    }
    let uid = String::from_utf8(output.stdout).context("decoding the current user ID")?;
    // LaunchAgents for the logged-in GUI session use the `gui/<uid>` domain.
    Ok(format!("gui/{}", uid.trim()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{EndpointConfig, HeaderEnvRef};

    #[test]
    fn systemd_unit_quotes_special_paths_and_references_env_file() {
        let unit = render_systemd_user_unit(
            "/opt/ws model/wsmp",
            "/home/user/.config/ws-model-proxy/service.env",
        );
        assert!(unit.contains("ExecStart=\"/opt/ws model/wsmp\" daemon start --foreground"));
        assert!(unit.contains("EnvironmentFile=-/home/user/.config/ws-model-proxy/service.env"));
        assert!(unit.contains("Restart=on-failure"));
        assert!(unit.contains("WantedBy=default.target"));
        assert!(!unit.contains("Environment=WSMP_"));
    }

    #[test]
    fn systemd_quote_arg_escapes_percent_and_quotes() {
        assert_eq!(systemd_quote_arg("/usr/bin/wsmp"), "/usr/bin/wsmp");
        assert_eq!(systemd_quote_arg("/tmp/a\"b%c"), "\"/tmp/a\\\"b%%c\"");
    }

    #[test]
    fn launch_agent_plist_uses_wrapper_and_escapes_xml() {
        let label = "com.flycockpit.wsmp";
        let plist = render_launch_agent_plist(
            label,
            "/tmp/wsmp-service-run.sh",
            "/Users/test",
            "/Users/test/Library/Logs/ws-model-proxy/relay.out.log",
            "/Users/test/Library/Logs/ws-model-proxy/relay.err.log",
        );
        assert!(plist.contains(&format!("<string>{label}</string>")));
        assert!(plist.contains("<string>/tmp/wsmp-service-run.sh</string>"));
        assert!(plist.contains("<key>KeepAlive</key>"));
        assert!(plist.contains("<key>RunAtLoad</key>"));
        assert!(plist.contains("<true/>"));
        assert!(!plist.contains("EnvironmentVariables"));
        let escaped = render_launch_agent_plist(
            "label",
            "/tmp/a&b<c>.sh",
            "/Users/test",
            "/tmp/out",
            "/tmp/err",
        );
        assert!(escaped.contains("/tmp/a&amp;b&lt;c&gt;.sh"));
    }

    #[test]
    fn macos_wrapper_sources_env_file_and_execs_foreground_daemon() {
        let script = render_macos_service_wrapper(
            "/usr/local/bin/wsmp",
            "/Users/x/.config/ws-model-proxy/service.env",
        );
        assert!(script.starts_with("#!/bin/sh\n"));
        assert!(script.contains("ENV_FILE='/Users/x/.config/ws-model-proxy/service.env'"));
        assert!(script.contains(". \"$ENV_FILE\""));
        assert!(script.contains("exec '/usr/local/bin/wsmp' daemon start --foreground"));
    }

    #[test]
    fn required_env_names_include_token_and_headers_once() {
        let config = Config {
            cli_token_env: Some("WSMP_TOKEN".to_string()),
            endpoints: vec![EndpointConfig {
                headers: vec![
                    HeaderEnvRef {
                        name: "Authorization".to_string(),
                        env: "LOCAL_API_KEY".to_string(),
                    },
                    HeaderEnvRef {
                        name: "X-Extra".to_string(),
                        env: "LOCAL_API_KEY".to_string(),
                    },
                ],
                ..EndpointConfig::default()
            }],
            ..Config::default()
        };
        assert_eq!(
            required_service_env_names(&config),
            vec!["WSMP_TOKEN".to_string(), "LOCAL_API_KEY".to_string()]
        );
    }

    #[test]
    fn service_env_file_quotes_values_without_echoing_raw_newlines() {
        let body = format_service_env_file(&[("WSMP_TOKEN".to_string(), "a b\"c".to_string())])
            .expect("format");
        assert!(body.contains("WSMP_TOKEN=\"a b\\\"c\"\n"));
        assert!(
            format_service_env_file(&[("WSMP_TOKEN".to_string(), "x\ny".to_string())]).is_err()
        );
    }
}
