/**
 * Typed MCP tool manifest (Phase 5).
 *
 * EVERY descriptor here is the checked wire contract for one MCP tool:
 * the exact public name, the exact oRPC procedure (or extracted diagnostic
 * core) it invokes, its scope requirement, confirmation policy, feature
 * dependency, side-effect classification, input adapter, and safe output
 * projector. The completeness test (tool-manifest.test.ts) fails when:
 *   - the manifest's names differ from the checked read/write catalog in ANY
 *     way (extra, missing, or duplicated);
 *   - an `appRouter` leaf is neither a tool target nor an explicit exclusion;
 *   - a write tool lacks literal `mcp:write`, a destructive tool lacks
 *     `DELETE`, or an external/cost tool lacks `RUN`;
 *   - a target path does not resolve against the real router object;
 *   - a tool's advertised input schema differs from the one generated from
 *     its real procedure input schema plus its declared overlays.
 *
 * INPUT SCHEMA POLICY (#117): procedure-backed tools advertise their REAL
 * input, generated by ONE generator (input-schema.ts) from the procedure's
 * own zod schema with the MCP-owned overlays merged in (`confirm`,
 * forbidden/human-only fields that name the tool to use instead, ISO date
 * strings). Authors declare a {@link McpToolSpec}; they never write an
 * `inputSchema`. Runtime validation is unchanged: the SDK only applies the
 * loose overlay/size-bound validator, and the oRPC procedure remains the
 * SINGLE validation authority for everything else. Its BAD_REQUEST issues
 * reach the client as a sanitized `{ path, code, message }` list
 * (input-errors.ts) — never input values — so an agent can name the field it
 * got wrong.
 */

import type { StandardSchemaWithJSON } from "@modelcontextprotocol/server";
import type { AppRouterClient } from "@ws-model-proxy/api/routers/index";
import { z } from "zod";
import { runChatCompletionDiagnostic, runPoolMemberTest } from "../model-api/diagnostics.js";
import { FILE_BODY_MAX_BYTES } from "../relay/file-protocol.js";
import {
  adaptCliCommandResultInput,
  adaptCliCommandRunInput,
  adaptCliSupervisedStartInput,
  CLI_AGENT_ACTIVITY_NOTICE,
  CLI_COMMAND_OUTPUT_NOTICE,
  CLI_SUPERVISED_COMMAND_NOTICE,
  runForwarderCliCommand,
  runForwarderCliCommandResult,
  runForwarderCliSupervisedCommandStart,
} from "./cli-command-tools.js";
import {
  auditFileInputRefusal,
  FILE_TOOL_NOTES,
  FILE_TOOLS,
  type FileToolName,
  fileToolCoreShape,
  projectFileToolOutput,
  runForwarderCliFileTool,
} from "./cli-file-tools.js";
import type { McpRequestCredential } from "./cli-tool-access.js";
import {
  buildInputSchema,
  MCP_TOOL_INPUT_MAX_BYTES,
  type McpInputOverlay,
} from "./input-schema.js";

/** Endpoint-wide scope requirement. Write tools require literal `mcp:write`. */
export type McpToolScope = "read" | "write";

/**
 * Human-confirmation policy literal surfaced to the client:
 * - `DELETE` — destructive removal;
 * - `RUN` — externally visible or costly execution;
 * - `null` — ordinary mutation/read, no confirmation gate.
 */
export type McpToolConfirmation = "DELETE" | "RUN" | null;

/** Side-effect classification used by the coverage checks. */
export type McpToolClass = "pure" | "external" | "cost" | "destructive";

/** Everything the tool wrapper needs to execute a procedure-backed tool. */
export interface McpToolRunDeps {
  /** Internal latch: a supervised file id was registered synchronously. */
  claimDeliverDespiteAbort?: () => void;
  /** Verified user id (`sub`) — the ONLY identity the tools ever act for. */
  userId: string;
  /**
   * The verified request's OWNED admission signal (G1): diagnostic cores
   * thread it into their network work (relay attempts, the synthetic chat
   * Request) so client aborts / shutdown tear them down. CLI command run
   * passes it to the wait; an abort ends the wait, not the command.
   */
  signal?: AbortSignal;
  /**
   * Admission credential. CLI tools require capability-specific PAT consent
   * and scopes. OAuth and missing bindings are always refused.
   */
  credential: McpRequestCredential;
}

/** One checked tool descriptor. */
export interface McpToolDescriptor {
  /** Exact public MCP tool name (stable wire contract). */
  name: string;
  /** Exact oRPC procedure path or extracted-core identifier (documentation + checked). */
  target: string;
  /** Required scope: `read` (mcp:read or mcp:write) or `write` (literal mcp:write). */
  scope: McpToolScope;
  /** Confirmation policy literal (`DELETE` / `RUN` / null). */
  confirmation: McpToolConfirmation;
  /**
   * Feature flags the underlying procedure family depends on
   * (informational metadata; runtime enforcement stays in oRPC). More than
   * one entry when the procedure has SEVERAL conditional gates (G8a).
   */
  featureDependencies?: readonly string[];
  /** Side-effect class for coverage-artifact checks. */
  classification: McpToolClass;
  /**
   * Advertised input schema, GENERATED from the spec by input-schema.ts
   * (real procedure input + overlays; loose runtime validator).
   */
  inputSchema: StandardSchemaWithJSON;
  /** Input adapter (MCP args → procedure input). Runs AFTER confirm-stripping. */
  inputAdapter?: (input: unknown) => unknown;
  /** Safe output projector applied BEFORE redaction + caps + serialization. */
  outputProjector?: (output: unknown) => unknown;
  /** Procedure-backed tools: typed invocation through the per-request client. */
  invokeProcedure?: (client: AppRouterClient, input: unknown) => Promise<unknown>;
  /** Extracted-core tools: user-ID-bound application function invocation. */
  invokeCore?: (input: unknown, deps: McpToolRunDeps) => Promise<unknown>;
  /**
   * Extra sentence appended to the generated tool description.
   */
  descriptionNote?: string;
  /**
   * Called when a call to this tool is refused before its core runs (the input
   * validator rejected the input, or the confirmation literal is missing), so
   * the refusal can be audited. Metadata only: it receives the raw input and
   * the verified user and credential, never a device it could trust.
   * These tools validate in the wrapper so every refusal has a stable code.
   */
  auditInputRefusal?: (
    input: unknown,
    who: { userId: string; credential: McpRequestCredential },
  ) => void;
  /**
   * Deliver the core's result even if the admission signal aborts. CLI
   * command run uses this: abort ends the wait, not the command, and the
   * result must still carry `commandId`.
   */
  deliverDespiteAbort?: boolean;
  /** File writes await their core to learn whether it started a supervised request. */
  deliverDespiteAbortWhen?: (output: unknown) => boolean;
}

/**
 * One authored tool: a descriptor minus the generated `inputSchema`, plus the
 * MCP-owned input overlays. `buildDescriptor` is the only producer of
 * descriptors, so no tool can advertise a hand-written schema.
 */
export type McpToolSpec = Omit<McpToolDescriptor, "inputSchema"> & McpInputOverlay;

/** Turn one spec into its descriptor with the generated `inputSchema`. */
export function buildDescriptor(spec: McpToolSpec): McpToolDescriptor {
  const {
    forbiddenInputs,
    emptyArrayInputs,
    isoDateFields,
    coreShape,
    maxInputBytes,
    shapeIsAdvisory,
    ...descriptor
  } = spec;
  if (isoDateFields !== undefined && descriptor.inputAdapter !== undefined) {
    throw new Error(`MCP tool ${spec.name}: isoDateFields and inputAdapter are exclusive`);
  }
  return {
    ...descriptor,
    ...(isoDateFields === undefined ? {} : { inputAdapter: isoDateFieldsAdapter(isoDateFields) }),
    inputSchema: buildInputSchema({
      target: spec.target,
      confirmation: spec.confirmation,
      forbiddenInputs,
      emptyArrayInputs,
      isoDateFields,
      coreShape,
      maxInputBytes,
      shapeIsAdvisory,
    }),
  };
}

/**
 * Clean, field-naming MCP error thrown by input adapters (G3): JSON cannot
 * carry the `Date` arguments several procedures require, so descriptors
 * with date-valued fields convert ISO-8601 strings and reject anything
 * else with THIS error — the wrapper maps it to a stable in-band tool
 * error naming the field (never a raw adapter message).
 */
export class McpInvalidDateInputError extends Error {
  constructor(readonly field: string) {
    super(`field ${field} must be an ISO-8601 timestamp`);
    this.name = "McpInvalidDateInputError";
  }
}

// ---------------------------------------------------------------------------
// Input adapters (JSON → procedure input)
// ---------------------------------------------------------------------------

/**
 * Strict RFC 3339 UTC timestamp: `YYYY-MM-DDTHH:MM:SS[.f+]Z` — the ONLY
 * form the adapter accepts. No offsets, no date-only forms, no space
 * separators: everything else (including the local-time and missing-Z
 * variants JavaScript's `new Date()` would happily parse) is rejected so no
 * silent timezone or calendar normalization can reach Prisma.
 */
const RFC3339_UTC_TIMESTAMP = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(\.\d+)?Z$/;

const DAYS_IN_MONTH = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31] as const;

function isLeapYear(year: number): boolean {
  return (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;
}

/**
 * Parse one RFC 3339 UTC timestamp with FULL component validation and
 * construction via `Date.UTC` — impossible calendar dates (Feb 30, Apr 31,
 * Feb 29 on a non-leap year), hours > 23, or minutes/seconds > 59 are
 * REJECTED instead of being normalized into the next valid day by
 * JavaScript's permissive `Date` parsing. Returns `null` for any value that
 * is not a real UTC calendar timestamp in the accepted shape.
 */
function parseStrictRfc3339Utc(value: string): Date | null {
  const match = RFC3339_UTC_TIMESTAMP.exec(value);
  if (match === null) return null;
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const hour = Number(match[4]);
  const minute = Number(match[5]);
  const second = Number(match[6]);
  if (month < 1 || month > 12) return null;
  const maxDay = month === 2 && isLeapYear(year) ? 29 : (DAYS_IN_MONTH[month - 1] ?? 30);
  if (day < 1 || day > maxDay) return null;
  if (hour > 23 || minute > 59 || second > 59) return null;
  // Fractional seconds: cut to milliseconds — never round (G3 pass 4).
  // Rounding a fraction like .9999 to 1000 ms increments the Date.UTC
  // second/minute/hour/day/year BEFORE `setUTCFullYear(year)` below
  // overwrites the rolled-over year, corrupting 2026-12-31T23:59:59.9999Z
  // into 2026-01-01 (wrong by ~a year on filters and destructive
  // staleBefore guards). Truncation is deterministic, never crosses a
  // calendar boundary, and matches millisecond `Date` precision. The
  // fraction digits are sliced as a STRING (padded to three places) so
  // binary floating-point artifacts (0.123 * 1000 === 122.999...) cannot
  // perturb the result.
  const millis = match[7] !== undefined ? Number(`${match[7].slice(1, 4).padEnd(3, "0")}`) : 0;
  // `Date.UTC` maps years 0-99 to 1900-1999; construct inside the safe
  // range and set the real year explicitly so 0000-0099 stay exact.
  const date = new Date(Date.UTC(2000, month - 1, day, hour, minute, second, millis));
  date.setUTCFullYear(year);
  return date;
}

/**
 * Adapt ISO-8601 timestamp STRINGS on the named fields to `Date` objects
 * (G3): the procedure's `z.date()` schema is the authority, but JSON can
 * only carry strings — without this adapter every timestamp filter
 * (`relay_requests_list` createdAfter/Before, the `staleBefore` guards)
 * would fail procedure validation with a generic BAD_REQUEST. ONLY strict
 * RFC 3339 UTC timestamps are accepted; anything else — non-string values,
 * `null` (the underlying schemas are `z.date().optional()`, where `null` is
 * invalid, and deleting it would silently remove the guard), a date-only
 * form, an offset form, or an impossible calendar date — is rejected with a
 * clean field-naming error BEFORE any procedure call. Absent fields pass
 * through untouched.
 */
export function isoDateFieldsAdapter(fields: readonly string[]): (input: unknown) => unknown {
  return (input) => {
    if (input === null || typeof input !== "object" || Array.isArray(input)) return input;
    const record = { ...(input as Record<string, unknown>) };
    for (const field of fields) {
      const value = record[field];
      if (value === undefined) continue;
      if (value instanceof Date) continue;
      if (typeof value !== "string") throw new McpInvalidDateInputError(field);
      const parsed = parseStrictRfc3339Utc(value);
      if (parsed === null || Number.isNaN(parsed.getTime())) {
        throw new McpInvalidDateInputError(field);
      }
      record[field] = parsed;
    }
    return record;
  };
}

// ---------------------------------------------------------------------------
// MCP-owned input overlays (merged over each procedure's real input schema by
// the generator in input-schema.ts; nothing here sets `inputSchema` by hand)
// ---------------------------------------------------------------------------

export { MCP_TOOL_INPUT_MAX_BYTES };

/**
 * `forwarder_cli_file_write` advertises `content` at most
 * {@link FILE_BODY_MAX_BYTES} DECODED. Base64 encodes 3 bytes into 4
 * characters, so a 1 MiB body arrives as ~1.4 MiB of JSON text: its first-stage
 * input bound is sized for the ENCODED form (4/3 of the cap plus headroom for
 * the other fields); the decoded body stays capped at {@link FILE_BODY_MAX_BYTES}
 * in `adaptFileToolInput`. The raw HTTP body is separately capped at 1 MiB by
 * `mcpBodyCap` (`apps/server/src/mcp-rate-limit.ts`), so this bound is budget,
 * not framing.
 */
const FILE_WRITE_FIELD_HEADROOM_BYTES = 64 * 1024;
const FILE_WRITE_INPUT_MAX_BYTES =
  Math.ceil((FILE_BODY_MAX_BYTES * 4) / 3) + FILE_WRITE_FIELD_HEADROOM_BYTES;

/**
 * The owner's external-fallback switches (`fallbackEnabled`,
 * `fallbackForGrantees`) change who pays for external provider use, so MCP
 * changes them ONLY through `forwarder_pool_fallback_update`, whose
 * description states the cost effect and whose every change is audited
 * (owner decision on issue #67). The general pool tools reject them; the
 * advertised schema names the replacement tool on each field.
 */
const POOL_FALLBACK_TOOL_MESSAGE =
  "External fallback switches are changed only with forwarder_pool_fallback_update.";

const POOL_FALLBACK_SWITCH_INPUTS = {
  fallbackEnabled: POOL_FALLBACK_TOOL_MESSAGE,
  fallbackForGrantees: POOL_FALLBACK_TOOL_MESSAGE,
} as const;

/**
 * Guarded create turns fallback on implicitly when it attaches provider
 * (external) members, so MCP may use it only for local-only pools. External
 * members can still be attached with `forwarder_provider_member_add` (which
 * never turns fallback on) and fallback turned on with
 * `forwarder_pool_fallback_update`.
 */
const GUARDED_EXTERNAL_MEMBERS_MESSAGE =
  "Attach external members with forwarder_provider_member_add, then turn fallback on with forwarder_pool_fallback_update.";

/**
 * The OpenRouter data-collection opt-out (decision D9) is human-only: an
 * agent must never relax the account's privacy routing. The account write
 * procedures do not accept it either (it has its own excluded procedure);
 * advertising it as forbidden makes the refusal explicit.
 */
const HUMAN_ONLY_DATA_COLLECTION_MESSAGE =
  "The OpenRouter data-collection setting can be changed only by a person in the dashboard.";

const DATA_COLLECTION_INPUTS = {
  allowDataCollection: HUMAN_ONLY_DATA_COLLECTION_MESSAGE,
} as const;

/** Cost statement carried by the fallback write tool's description (issue #67). */
export const POOL_FALLBACK_COST_NOTICE =
  "COST: fallbackEnabled=true lets requests for owner/pool:external be sent to the pool's external provider members, billed to YOUR provider accounts (real money, and request data leaves this deployment). fallbackForGrantees=true makes YOU pay for external use by every user the pool is shared with. externalAfterWaitMs sets how long an :external request waits for local capacity before paying for a provider: lower values spend more. Turning a switch off never costs anything. Every change is recorded as a POOL_FALLBACK_UPDATED provider audit event. PRECONDITIONS: turning fallbackEnabled on needs provider egress enabled on this deployment (otherwise the call fails with Not found) and, on every external member, an active LIMITED or UNLIMITED per-attempt concurrency policy with an activation audit trail; a new externalAfterWaitMs cannot exceed the pool's local wait budget (these two fail with a plain Invalid input error that has no field list, because the input itself is valid).";

/**
 * Cost statement for the general pool tools, which still accept
 * `externalAfterWaitMs` (K1-1: the owner decision requires the cost of every
 * writable fallback field to be stated where it can be written).
 */
export const POOL_EXTERNAL_WAIT_COST_NOTICE =
  "fallbackEnabled and fallbackForGrantees are rejected here: use forwarder_pool_fallback_update. COST: externalAfterWaitMs sets how long an owner/pool:external request waits for local capacity before it is sent to a paid external provider billed to YOUR provider accounts: lower values spend more. Changes are recorded as POOL_FALLBACK_UPDATED provider audit events.";

// ---------------------------------------------------------------------------
// Procedure invocation helper
// ---------------------------------------------------------------------------

/**
 * Build the typed invocation for one procedure leaf.
 *
 * The ONE `input as I` cast in the entire manifest is this seam: the input
 * arrived as unknown JSON from the wire, and the procedure's own zod schema
 * revalidates it server-side before any handler runs — that validator, not
 * this cast, is the input authority (see the INPUT SCHEMA POLICY above; the
 * advertised JSON Schema is generated from that same procedure schema).
 */
export function procedureInvoker<I, O>(
  select: (client: AppRouterClient) => (input: I) => Promise<O>,
): (client: AppRouterClient, input: unknown) => Promise<O> {
  return (client, input) => select(client)(input as I);
}

// ---------------------------------------------------------------------------
// Safe output projectors
// ---------------------------------------------------------------------------

/**
 * Explicit safe projection for provider credential rows: keep ONLY the
 * display-safe metadata fields. The procedure already selects exactly these
 * columns, but the projection is the MCP-side contract — a future select
 * widening cannot leak through this tool.
 */
const SAFE_CREDENTIAL_FIELDS = [
  "id",
  "createdAt",
  "credentialType",
  "keyVersion",
  "displaySuffix",
  "status",
  "replacedAt",
  "lastUsedAt",
  "revokedAt",
] as const;

function projectCredentialRows(output: unknown): unknown {
  if (!Array.isArray(output)) return output;
  return output.map((row) => {
    if (row === null || typeof row !== "object") return row;
    const record = row as Record<string, unknown>;
    const projected: Record<string, unknown> = {};
    for (const field of SAFE_CREDENTIAL_FIELDS) {
      if (field in record) projected[field] = record[field];
    }
    return projected;
  });
}

// ---------------------------------------------------------------------------
// Feature dependencies
// ---------------------------------------------------------------------------

const PROVIDER_EGRESS_FEATURE = "WMP_PUBLIC_PROVIDER_EGRESS_ENABLED";

// ---------------------------------------------------------------------------
// The checked catalog — every entry's name/target pair is pinned against the
// checked read/write catalog by tool-manifest.test.ts.
// ---------------------------------------------------------------------------

/**
 * One node file tool (relay 2.8, #103) as an authored spec; `buildDescriptor`
 * generates its `inputSchema` (#117) from `coreShape`. Read-class tools are
 * scope `read`, pure, unconfirmed; write-class tools are scope `write`,
 * external, `RUN` (`DELETE` for delete). All nine are extracted cores that go
 * through the one file-op relay path; visibility is the PAT-only
 * `cliToolAllowed` predicate.
 */
function isSupervisedFileStart(output: unknown): boolean {
  return (
    output !== null &&
    typeof output === "object" &&
    "kind" in output &&
    output.kind === "supervised" &&
    "commandId" in output
  );
}

function fileToolSpec(name: FileToolName): McpToolSpec {
  const entry = FILE_TOOLS.find((tool) => tool.name === name);
  if (!entry) throw new Error(`unknown file tool ${name}`);
  const { op } = entry;
  const readClass = op === "read" || op === "stat" || op === "list" || op === "search";
  return {
    name,
    target: entry.target,
    scope: readClass ? "read" : "write",
    confirmation: readClass ? null : op === "delete" ? "DELETE" : "RUN",
    classification: readClass ? "pure" : op === "delete" ? "destructive" : "external",
    ...(!readClass
      ? { deliverDespiteAbort: true, deliverDespiteAbortWhen: isSupervisedFileStart }
      : {}),
    descriptionNote: FILE_TOOL_NOTES[name],
    coreShape: fileToolCoreShape(name),
    // The core enforces the strict shape: refusals are audited and name the field.
    shapeIsAdvisory: true,
    auditInputRefusal: (input, who) => auditFileInputRefusal(op, input, who),
    ...(op === "write" ? { maxInputBytes: FILE_WRITE_INPUT_MAX_BYTES } : {}),
    invokeCore: (input, deps) => runForwarderCliFileTool(op, input, deps),
    outputProjector: projectFileToolOutput,
  };
}

const READ_TOOLS: readonly McpToolSpec[] = [
  {
    name: "app_config_get",
    target: "appConfig",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.appConfig),
  },
  {
    name: "forwarder_guarded_candidates_list",
    target: "forwarderManagement.listGuardedOverflowCandidates",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.listGuardedOverflowCandidates,
    ),
  },
  {
    name: "forwarder_cli_devices_list",
    target: "forwarderManagement.listCliDevices",
    scope: "read",
    confirmation: null,
    classification: "pure",
    descriptionNote:
      "features.commands.effectiveMode is what an agent can run now: the stricter of the dashboard grant (mode) and the CLI's own wsmp config (deviceMode). features.commands.refusals says, per tool, what the relay would refuse right now, in its own check order: refusals.headless (forwarder_cli_command_run) and refusals.supervised (forwarder_cli_supervised_command_start) are null when admitted, else grant_disabled (dashboard grant), grant_supervised_only or cli_supervised_only (the relay's supervised_only: headless needs unsupervised, and the dashboard grant, or else wsmp config, is only supervised), offline (CLI not connected or too old), feature_disabled (wsmp config set-mcp-commands), or unsupported (no terminal support, supervised only). available is true when either tool would be admitted. A command token also needs mcp:write and allowCliCommands. fileTools follows that effective mode: unsupervised admits read/write; supervised/off admit reads only with the dashboard mcpFileRead grant, live CLI mcpFileRead and fileRootsConfigured. A read-only PAT needs allowCliFileRead and mcp:read for the four read tools; write tools retain allowCliCommands and mcp:write. Reported fields reportedMcpFileRead/reportedFileRoots describe CLI configuration; missing live features never authorize reads.",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.listCliDevices),
  },
  {
    name: "forwarder_cli_activity_list",
    target: "cliAgentActivity.list",
    scope: "read",
    confirmation: null,
    classification: "pure",
    descriptionNote: CLI_AGENT_ACTIVITY_NOTICE,
    invokeProcedure: procedureInvoker((client) => client.cliAgentActivity.list),
  },
  {
    name: "forwarder_device_metrics_get",
    target: "forwarderManagement.getCliDeviceMetrics",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.getCliDeviceMetrics),
  },
  {
    name: "forwarder_pool_routing_rules_get",
    descriptionNote:
      "Read pool rules, member live engine load, and engineLoad.kvBudget (reported/effective tokens, eviction cut, floor, observation/expiry times and active state). engineLoad also reports customMode (observe/enforce), loadSource, signals, enforced, and live.kvOccupancy (display only; never FULL or eviction evidence). Custom FULL starts observe-only.",
    target: "forwarderManagement.getPoolRoutingRules",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.getPoolRoutingRules),
  },
  {
    name: "forwarder_engine_load_history_get",
    descriptionNote:
      "30-minute live engine-load history (10 s buckets) for a pool or capacity the caller owns. Returns per-member series (max running/waiting/kvUsage/kvOccupancy/slotsBusy, summed prefix deltas, source, gap markers), signals, the effective KV FULL threshold, and reported K. kvOccupancy is display only. A foreign pool or capacity returns NOT_FOUND.",
    target: "forwarderManagement.getEngineLoadHistory",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.getEngineLoadHistory),
  },
  {
    name: "forwarder_model_pools_list",
    target: "forwarderManagement.listModelPools",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.listModelPools),
  },
  {
    name: "forwarder_pool_fallback_get",
    target: "poolFallback.get",
    scope: "read",
    confirmation: null,
    classification: "pure",
    descriptionNote:
      "Owners get the pool's external fallback switches, external members in fallback order, and the own-key request count. Grantees get whether owner-paid fallback is available to them (provider types only) and their own-key route.",
    invokeProcedure: procedureInvoker((client) => client.poolFallback.get),
  },
  {
    name: "forwarder_affinity_stats_get",
    target: "forwarderManagement.cacheAffinityStats",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.cacheAffinityStats),
  },
  {
    name: "forwarder_pool_cache_stats_get",
    target: "forwarderManagement.poolCacheStats",
    scope: "read",
    confirmation: null,
    classification: "pure",
    descriptionNote:
      "Prompt-cache hit rate for a pool (or one member) over lastMinutes or lastDays. hitRate is cacheReadTokens/cacheKnownInputTokens capped at 1, or null when nothing reported cache usage. continuationHitRate is the same ratio for matched-affinity requests (null for windows that predate those columns). coverage is cacheKnownRequests/requests. Compare continuationHitRate for equal windows before and after a change, and check coverage first. Owners see every requester on their pools; grantees see only their own. A foreign pool or member returns NOT_FOUND.",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.poolCacheStats),
  },
  {
    name: "forwarder_models_visible_list",
    target: "forwarderManagement.visibleModels",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.visibleModels),
  },
  {
    name: "provider_accounts_list",
    target: "providerManagement.listAccounts",
    scope: "read",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.listAccounts),
  },
  {
    name: "provider_models_list",
    target: "providerManagement.listModels",
    scope: "read",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.listModels),
  },
  {
    name: "provider_pricing_versions_list",
    target: "providerManagement.listPricingVersions",
    scope: "read",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.listPricingVersions),
  },
  {
    name: "provider_credentials_list",
    target: "providerManagement.listCredentials",
    scope: "read",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    outputProjector: projectCredentialRows,
    invokeProcedure: procedureInvoker((client) => client.providerManagement.listCredentials),
  },
  {
    name: "provider_audit_events_list",
    target: "providerManagement.listAuditEvents",
    scope: "read",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.listAuditEvents),
  },
  {
    name: "provider_usage_page_list",
    target: "providerManagement.listUsageReportPage",
    scope: "read",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.listUsageReportPage),
  },
  {
    name: "provider_usage_totals_get",
    target: "providerManagement.getUsageTotals",
    scope: "read",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.getUsageTotals),
  },
  {
    name: "provider_budget_activity_list",
    target: "providerManagement.listBudgetActivity",
    scope: "read",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.listBudgetActivity),
  },
  {
    name: "provider_attempt_events_list",
    target: "providerManagement.listProviderAttemptEvents",
    scope: "read",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker(
      (client) => client.providerManagement.listProviderAttemptEvents,
    ),
  },
  {
    name: "provider_attempts_list",
    target: "providerManagement.listProviderAttempts",
    scope: "read",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.listProviderAttempts),
  },
  {
    name: "provider_budget_policies_list",
    target: "providerManagement.listBudgetPolicies",
    scope: "read",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.listBudgetPolicies),
  },
  {
    name: "capacity_records_list",
    target: "capacityManagement.list",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.capacityManagement.list),
  },
  {
    name: "capacity_audit_list",
    target: "capacityManagement.listAudit",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.capacityManagement.listAudit),
  },
  {
    name: "model_api_tokens_list",
    target: "modelApiTokens.list",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.modelApiTokens.list),
  },
  {
    name: "model_api_tokens_preview",
    target: "modelApiTokens.preview",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.modelApiTokens.preview),
  },
  {
    name: "cli_tokens_list",
    target: "cliCredentials.listTokens",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.cliCredentials.listTokens),
  },
  {
    name: "relay_requests_list",
    target: "relayMetadata.listOwn",
    scope: "read",
    confirmation: null,
    classification: "pure",
    // G3: JSON→Date adaptation for the timestamp filters (z.date() inputs).
    isoDateFields: ["createdAfter", "createdBefore"],
    invokeProcedure: procedureInvoker((client) => client.relayMetadata.listOwn),
  },
  // --- dashboard overview (prompt-free aggregates) ---
  // Same procedure and scope as the web Overview: traffic on resources the
  // caller owns (any requester), plus the caller's own usage of pools shared
  // with them as per-pool totals; never other requesters' shared-pool usage.
  {
    name: "overview_metrics",
    target: "overview.metrics",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.overview.metrics),
  },
  {
    name: "overview_health",
    target: "overview.health",
    scope: "read",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.overview.health),
  },
  // --- node file tools, read class (relay 2.8; PAT-only) ---
  fileToolSpec("forwarder_cli_file_read"),
  fileToolSpec("forwarder_cli_file_stat"),
  fileToolSpec("forwarder_cli_dir_list"),
  fileToolSpec("forwarder_cli_file_search"),
];

/**
 * Chat diagnostic `messages` (G5 input parity, pass 5): a plain array of
 * `unknown` entries — NO minimum count and NO per-entry (role) validation.
 * Full input parity with the shared HTTP diagnostic path
 * (chatTestCompletionsHandler / prepareJsonModeledRequest), which validates
 * JSON and the model then forwards — it relays `messages: []` and roleless
 * entries verbatim (pinned by the HTTP regression), so the production
 * chat-test core owns the real per-entry validation. Mirroring per-entry
 * object schemas here would both diverge from HTTP again and let an
 * abusive input produce one zod issue PER ENTRY, which the installed SDK
 * echoes into an unbounded tool result. First-stage bounds enforce the
 * established 64 KiB byte budget and the shared 256-level JSON depth limit
 * before serialization (withInputSizeBound).
 */
const CHAT_MESSAGES_SCHEMA = z.array(z.unknown());

const WRITE_TOOLS: readonly McpToolSpec[] = [
  // --- forwarder management (writes) ---
  {
    name: "forwarder_guarded_pool_create",
    target: "forwarderManagement.createGuardedModelPool",
    scope: "write",
    confirmation: null,
    classification: "pure",
    // D-K: no external members here, because attaching them turns fallback on.
    emptyArrayInputs: { providerModels: GUARDED_EXTERNAL_MEMBERS_MESSAGE },
    descriptionNote:
      "Local members only: attaching external (provider) members here would turn external fallback on implicitly. Attach them with forwarder_provider_member_add and turn fallback on with forwarder_pool_fallback_update.",
    // G8a: conditional provider-egress gate (providerModels.length > 0).
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.createGuardedModelPool,
    ),
  },
  {
    name: "forwarder_cli_device_rename",
    target: "forwarderManagement.renameCliDevice",
    scope: "write",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.renameCliDevice),
  },
  {
    name: "forwarder_cli_metadata_remove",
    target: "forwarderManagement.removeCliDeviceMetadata",
    scope: "write",
    confirmation: "DELETE",
    classification: "destructive",
    // G3: JSON→Date adaptation for the staleness guard (z.date() input).
    isoDateFields: ["staleBefore"],
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.removeCliDeviceMetadata,
    ),
  },
  {
    name: "forwarder_endpoint_metadata_remove",
    target: "forwarderManagement.removeEndpointMetadata",
    scope: "write",
    confirmation: "DELETE",
    classification: "destructive",
    // G3: JSON→Date adaptation for the staleness guard (z.date() input).
    isoDateFields: ["staleBefore"],
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.removeEndpointMetadata,
    ),
  },
  {
    name: "forwarder_model_metadata_remove",
    target: "forwarderManagement.removeDiscoveredModelMetadata",
    scope: "write",
    confirmation: "DELETE",
    classification: "destructive",
    // G3: JSON→Date adaptation for the staleness guard (z.date() input).
    isoDateFields: ["staleBefore"],
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.removeDiscoveredModelMetadata,
    ),
  },
  {
    name: "forwarder_affinity_clear",
    target: "forwarderManagement.clearCacheAffinity",
    scope: "write",
    confirmation: "DELETE",
    classification: "destructive",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.clearCacheAffinity),
  },
  {
    name: "forwarder_model_pool_create",
    target: "forwarderManagement.createModelPool",
    scope: "write",
    confirmation: null,
    classification: "pure",
    // fallbackEnabled / fallbackForGrantees go through the dedicated,
    // cost-described forwarder_pool_fallback_update; externalAfterWaitMs and
    // cacheHolderWaitMs and the warm-session protection settings (S-C) pass through (audited). Token external consent is
    // never an MCP arg.
    forbiddenInputs: POOL_FALLBACK_SWITCH_INPUTS,
    descriptionNote: POOL_EXTERNAL_WAIT_COST_NOTICE,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.createModelPool),
  },
  {
    name: "forwarder_pool_routing_rules_set",
    target: "forwarderManagement.setPoolRoutingRules",
    scope: "write",
    confirmation: "RUN",
    // A `full` rule can send `:external` callers to paid external providers.
    classification: "cost",
    descriptionNote:
      "Replaces the pool's whole rule list: [{metric, labels?, aggregate: 'max', op: '>'|'>='|'<'|'<=', threshold, effect: 'full'|'avoid'}]. Discover metric names with forwarder_device_metrics_get or forwarder_pool_routing_rules_get.",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.setPoolRoutingRules),
  },
  {
    name: "forwarder_pool_member_engine_load_set",
    target: "forwarderManagement.setPoolMemberEngineLoad",
    scope: "write",
    confirmation: "RUN",
    // Engine-load FULL can send `:external` callers to paid external providers.
    classification: "cost",
    descriptionNote:
      "{poolMemberId, mode: 'auto'|'off', customMode?: 'observe'|'enforce', kvFullThreshold?: 0-1 or null}. 'off' ignores the engine's live load (endpoint.load) for that member; lease counts still apply. customMode observe reports would-be FULL without gating admission; enforce lets custom FULL gate. Custom FULL starts observe-only. Read the live load with forwarder_pool_routing_rules_get.",
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.setPoolMemberEngineLoad,
    ),
  },
  {
    name: "forwarder_device_metric_sources_set",
    target: "forwarderManagement.setCliDeviceMetricSources",
    scope: "write",
    confirmation: "RUN",
    // Defines commands that run on the person's machine.
    classification: "external",
    descriptionNote:
      "Only for devices whose MCP command mode is unsupervised, and only for a personal token minted with the CLI commands option (like forwarder_cli_command_run). The CLI runs a source only with its local opt-in and after the person approves the exact command (wsmp metrics approve <name> --sha256 <hash>); a changed command needs approval again.",
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.setCliDeviceMetricSources,
    ),
  },
  {
    name: "forwarder_device_engine_adapters_set",
    target: "forwarderManagement.setCliDeviceEngineAdapters",
    scope: "write",
    confirmation: "RUN",
    classification: "external",
    descriptionNote:
      "Only for devices whose MCP command mode is unsupervised, and only for a personal token minted with the CLI commands option. Replaces the device's remote engine adapters. The CLI runs one only with its separate local opt-in (allowRemoteEngineAdapters; metric-source opt-in is not enough) and after the person approves the canonical spec (wsmp endpoints adapter approve <slug> --sha256 <hash>); a changed spec needs approval again. Custom FULL starts observe-only.",
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.setCliDeviceEngineAdapters,
    ),
  },
  {
    name: "forwarder_device_engine_adapters_clear",
    target: "forwarderManagement.clearCliDeviceEngineAdapters",
    scope: "write",
    confirmation: "RUN",
    classification: "external",
    descriptionNote:
      "Clears remotely defined engine adapters for an unsupervised device. Same credential and mode gate as forwarder_device_engine_adapters_set.",
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.clearCliDeviceEngineAdapters,
    ),
  },
  {
    name: "forwarder_model_pool_update",
    target: "forwarderManagement.updateModelPool",
    scope: "write",
    confirmation: null,
    classification: "pure",
    // fallbackEnabled / fallbackForGrantees go through the dedicated,
    // cost-described forwarder_pool_fallback_update; externalAfterWaitMs and
    // cacheHolderWaitMs and the warm-session protection settings (S-C) pass through (audited). Capacity policy fields are
    // always admitted.
    forbiddenInputs: POOL_FALLBACK_SWITCH_INPUTS,
    descriptionNote: POOL_EXTERNAL_WAIT_COST_NOTICE,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.updateModelPool),
  },
  {
    name: "forwarder_pool_fallback_update",
    target: "poolFallback.update",
    scope: "write",
    // Owner decision (issue #67): an ordinary mcp:write tool, no per-change
    // confirmation; the cost is stated here and every change is audited.
    confirmation: null,
    classification: "pure",
    descriptionNote: POOL_FALLBACK_COST_NOTICE,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    invokeProcedure: procedureInvoker((client) => client.poolFallback.update),
  },
  {
    name: "forwarder_model_pool_delete",
    target: "forwarderManagement.deleteModelPool",
    scope: "write",
    confirmation: "DELETE",
    classification: "destructive",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.deleteModelPool),
  },
  {
    name: "forwarder_pool_member_add",
    target: "forwarderManagement.addPoolMember",
    scope: "write",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.addPoolMember),
  },
  {
    name: "forwarder_provider_member_add",
    target: "forwarderManagement.addProviderPoolMember",
    scope: "write",
    confirmation: null,
    classification: "pure",
    // G8a: the provider-egress gate is UNCONDITIONAL for this procedure.
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.addProviderPoolMember),
  },
  {
    name: "forwarder_pool_member_update",
    target: "forwarderManagement.updatePoolMember",
    scope: "write",
    confirmation: null,
    classification: "pure",
    // G8a: conditional provider-egress gate (provider model targets).
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.updatePoolMember),
  },
  {
    name: "forwarder_provider_member_reorder",
    target: "forwarderManagement.reorderProviderPoolMember",
    scope: "write",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.reorderProviderPoolMember,
    ),
  },
  {
    name: "forwarder_pool_member_remove",
    target: "forwarderManagement.removePoolMember",
    scope: "write",
    confirmation: "DELETE",
    classification: "destructive",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.removePoolMember),
  },
  {
    name: "forwarder_model_capabilities_update",
    target: "forwarderManagement.updateDiscoveredModelCapabilities",
    scope: "write",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.updateDiscoveredModelCapabilities,
    ),
  },
  {
    name: "forwarder_model_capability_profile_set",
    target: "forwarderManagement.setDiscoveredModelCapabilityProfile",
    scope: "write",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.setDiscoveredModelCapabilityProfile,
    ),
  },
  {
    name: "forwarder_model_attachment_limit_update",
    target: "forwarderManagement.updateDiscoveredModelAttachmentLimit",
    scope: "write",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.updateDiscoveredModelAttachmentLimit,
    ),
  },
  {
    name: "forwarder_pool_grant_create",
    target: "forwarderManagement.grantPoolAccessByEmail",
    scope: "write",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.grantPoolAccessByEmail,
    ),
  },
  {
    // S-C per-grant routing: warm-session protection override and queue
    // priority. Owner-only through the procedure (owned pool + owned grant).
    name: "forwarder_pool_grant_update",
    target: "forwarderManagement.updatePoolGrant",
    scope: "write",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.forwarderManagement.updatePoolGrant),
  },
  {
    name: "forwarder_pool_grant_revoke",
    target: "forwarderManagement.revokePoolAccessByEmail",
    scope: "write",
    confirmation: "DELETE",
    classification: "destructive",
    invokeProcedure: procedureInvoker(
      (client) => client.forwarderManagement.revokePoolAccessByEmail,
    ),
  },
  // --- provider management (writes) ---
  {
    name: "provider_account_create",
    target: "providerManagement.createAccount",
    scope: "write",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    forbiddenInputs: DATA_COLLECTION_INPUTS,
    invokeProcedure: procedureInvoker((client) => client.providerManagement.createAccount),
  },
  {
    name: "provider_account_update",
    target: "providerManagement.updateAccount",
    scope: "write",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    forbiddenInputs: DATA_COLLECTION_INPUTS,
    descriptionNote:
      "Changing an OpenRouter account to another providerType is refused (it would drop the account's data_collection: deny privacy routing); only a person can do that in the dashboard.",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.updateAccount),
  },
  {
    name: "provider_account_enabled_set",
    target: "providerManagement.setAccountEnabled",
    scope: "write",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.setAccountEnabled),
  },
  {
    name: "provider_account_delete",
    target: "providerManagement.deleteAccount",
    scope: "write",
    confirmation: "DELETE",
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "destructive",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.deleteAccount),
  },
  {
    name: "provider_model_create",
    target: "providerManagement.createModel",
    scope: "write",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.createModel),
  },
  {
    name: "provider_model_update",
    target: "providerManagement.updateModel",
    scope: "write",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.updateModel),
  },
  {
    name: "provider_model_delete",
    target: "providerManagement.deleteModel",
    scope: "write",
    confirmation: "DELETE",
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "destructive",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.deleteModel),
  },
  {
    name: "provider_pricing_version_create",
    target: "providerManagement.createPricingVersion",
    scope: "write",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.createPricingVersion),
  },
  {
    name: "provider_pricing_version_update",
    target: "providerManagement.updatePricingVersion",
    scope: "write",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.updatePricingVersion),
  },
  {
    name: "provider_pricing_version_activate",
    target: "providerManagement.activatePricingVersion",
    scope: "write",
    confirmation: "RUN",
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "external",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.activatePricingVersion),
  },
  {
    name: "provider_pricing_version_retire",
    target: "providerManagement.retirePricingVersion",
    scope: "write",
    confirmation: "RUN",
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "external",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.retirePricingVersion),
  },
  {
    name: "provider_pricing_version_delete",
    target: "providerManagement.deletePricingVersion",
    scope: "write",
    confirmation: "DELETE",
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "destructive",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.deletePricingVersion),
  },
  {
    name: "provider_credential_revoke",
    target: "providerManagement.revokeCredential",
    scope: "write",
    confirmation: "DELETE",
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "destructive",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.revokeCredential),
  },
  {
    name: "provider_credential_reencrypt",
    target: "providerManagement.rotateCredential",
    scope: "write",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.rotateCredential),
  },
  {
    name: "provider_credential_test",
    target: "providerManagement.testCredential",
    scope: "write",
    confirmation: "RUN",
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "cost",
    descriptionNote:
      "Result outcome SUCCESS means an endpoint known to require the key accepted it. FAILURE with reason INVALID_CREDENTIAL means the provider answered 401: the key was not accepted. INCONCLUSIVE means the key is neither confirmed nor refused: reason INSUFFICIENT_PERMISSION (HTTP 403) means the key may lack permission to list models but may still work for inference; UNVERIFIED or UNEXPECTED_STATUS means this provider type has no endpoint known to check keys.",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.testCredential),
  },
  {
    name: "provider_budget_policy_create",
    target: "providerManagement.createBudgetPolicy",
    scope: "write",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.createBudgetPolicy),
  },
  {
    name: "provider_budget_policy_replace",
    target: "providerManagement.replaceBudgetPolicy",
    scope: "write",
    confirmation: null,
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.replaceBudgetPolicy),
  },
  {
    name: "provider_budget_policy_deactivate",
    target: "providerManagement.deactivateBudgetPolicy",
    scope: "write",
    confirmation: "DELETE",
    featureDependencies: [PROVIDER_EGRESS_FEATURE],
    classification: "destructive",
    invokeProcedure: procedureInvoker((client) => client.providerManagement.deactivateBudgetPolicy),
  },
  // --- capacity management (writes) ---
  {
    name: "capacity_record_create",
    target: "capacityManagement.create",
    scope: "write",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.capacityManagement.create),
  },
  {
    name: "capacity_record_update",
    target: "capacityManagement.update",
    scope: "write",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.capacityManagement.update),
  },
  {
    name: "capacity_record_remove",
    target: "capacityManagement.remove",
    scope: "write",
    confirmation: "DELETE",
    classification: "destructive",
    invokeProcedure: procedureInvoker((client) => client.capacityManagement.remove),
  },
  {
    name: "capacity_direct_policy_update",
    target: "capacityManagement.updateDirectPolicy",
    scope: "write",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.capacityManagement.updateDirectPolicy),
  },
  {
    name: "capacity_pool_policy_update",
    target: "capacityManagement.updatePoolPolicy",
    scope: "write",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.capacityManagement.updatePoolPolicy),
  },
  {
    name: "capacity_member_policy_update",
    target: "capacityManagement.updateMemberPolicy",
    scope: "write",
    confirmation: null,
    classification: "pure",
    invokeProcedure: procedureInvoker((client) => client.capacityManagement.updateMemberPolicy),
  },
  // --- token revocation (writes) ---
  {
    name: "model_api_token_revoke",
    target: "modelApiTokens.revoke",
    scope: "write",
    confirmation: "DELETE",
    classification: "destructive",
    invokeProcedure: procedureInvoker((client) => client.modelApiTokens.revoke),
  },
  {
    name: "cli_token_revoke",
    target: "cliCredentials.revokeToken",
    scope: "write",
    confirmation: "DELETE",
    classification: "destructive",
    invokeProcedure: procedureInvoker((client) => client.cliCredentials.revokeToken),
  },
  // --- extracted diagnostic cores (writes: external + cost) ---
  {
    name: "forwarder_pool_member_test",
    target: "core:model-api/runPoolMemberTest",
    scope: "write",
    confirmation: "RUN",
    classification: "cost",
    coreShape: { memberId: z.string().min(1) },
    inputAdapter: (input) =>
      typeof input === "object" && input !== null
        ? { memberId: (input as { memberId?: unknown }).memberId }
        : input,
    invokeCore: (input, deps) =>
      runPoolMemberTest({
        userId: deps.userId,
        memberId: (input as { memberId: string }).memberId,
        signal: deps.signal,
      }),
  },
  {
    name: "forwarder_chat_completion_test",
    target: "core:model-api/runChatCompletionDiagnostic",
    scope: "write",
    confirmation: "RUN",
    classification: "cost",
    coreShape: { model: z.string().min(1), messages: CHAT_MESSAGES_SCHEMA },
    invokeCore: (input, deps) =>
      runChatCompletionDiagnostic({
        userId: deps.userId,
        body: input as Record<string, unknown>,
        signal: deps.signal,
      }),
  },
  {
    name: "forwarder_cli_command_run",
    target: "core:forwarderCliCommandRun",
    scope: "write",
    confirmation: "RUN",
    classification: "external",
    descriptionNote: CLI_COMMAND_OUTPUT_NOTICE,
    deliverDespiteAbort: true,
    coreShape: {
      cliDeviceId: z.string(),
      command: z.string(),
      cwd: z.string().optional(),
      waitMs: z.number().optional(),
    },
    inputAdapter: adaptCliCommandRunInput,
    invokeCore: (input, deps) => runForwarderCliCommand(input, deps),
  },
  {
    name: "forwarder_cli_supervised_command_start",
    target: "core:forwarderCliSupervisedCommandStart",
    scope: "write",
    confirmation: "RUN",
    classification: "external",
    descriptionNote: `${CLI_SUPERVISED_COMMAND_NOTICE} ${CLI_COMMAND_OUTPUT_NOTICE}`,
    deliverDespiteAbort: true,
    coreShape: {
      cliDeviceId: z.string(),
      command: z.string(),
      cwd: z.string().optional(),
      reason: z.string().optional(),
      shareOutput: z.boolean().optional(),
    },
    inputAdapter: adaptCliSupervisedStartInput,
    invokeCore: (input, deps) => runForwarderCliSupervisedCommandStart(input, deps),
  },
  {
    name: "forwarder_cli_command_result",
    target: "core:forwarderCliCommandResult",
    scope: "write",
    confirmation: null,
    classification: "pure",
    descriptionNote: `Poll commands or supervised file requests by commandId. Files return file:{op,result} or error:{code,message,outcome?}; no diff/hunks or file error detail is returned. Every non-success after acceptance carries outcome unknown, including any CLI fileError code (conflict, not_found, io_error, cancelled or timeout), token inactivity and mode changes. Server termination after term.spawn dispatch is also unknown; started is true when the server received acceptance and null otherwise, since acceptance and apply may be in flight. Only undispatched admission/spawn-send failures and authoritative CLI decline/rejection/blocked done are definitively not applied; late reports cannot change finished file results. ${CLI_COMMAND_OUTPUT_NOTICE}`,
    coreShape: { commandId: z.string(), progress: z.boolean().optional() },
    inputAdapter: adaptCliCommandResultInput,
    invokeCore: (input, deps) => runForwarderCliCommandResult(input, deps),
  },
  // --- node file tools, write class (relay 2.8; PAT-only) ---
  fileToolSpec("forwarder_cli_file_edit"),
  fileToolSpec("forwarder_cli_file_write"),
  fileToolSpec("forwarder_cli_file_rename"),
  fileToolSpec("forwarder_cli_dir_create"),
  fileToolSpec("forwarder_cli_file_delete"),
];

/**
 * The checked catalog: exactly 35 read tools and 60 write tools
 * (81 procedure-backed + 14 extracted cores: 2 diagnostics, 3 CLI commands
 * and 9 node file tools (4 read, 5 write)).
 */
export const MCP_TOOL_MANIFEST: readonly McpToolDescriptor[] = [...READ_TOOLS, ...WRITE_TOOLS].map(
  buildDescriptor,
);

// ---------------------------------------------------------------------------
// Explicit first-release exclusions (Phase 5). Every `appRouter`
// leaf that is not a tool target above MUST appear here; the completeness
// test fails otherwise (a new unclassified procedure cannot ship silently).
// ---------------------------------------------------------------------------

export interface McpToolExclusion {
  /** Exact oRPC procedure path (or router, for whole-router exclusions). */
  target: string;
  /** Why the procedure is not an MCP tool in the first release. */
  reason: string;
}

export const MCP_TOOL_EXCLUSIONS: readonly McpToolExclusion[] = [
  {
    target: "auth.verifyEmailTransport",
    reason: "Auth-router surface; not a model-proxy operation.",
  },
  {
    target: "auth.updateLocale",
    reason: "Account identity management, not model-proxy operation.",
  },
  {
    target: "auth.passwordCapabilities",
    reason: "Auth-router surface; not a model-proxy operation.",
  },
  {
    target: "forwarderManagement.getProfileSlug",
    reason: "Profile-slug procedures are account identity management.",
  },
  {
    target: "forwarderManagement.previewProfileSlugChange",
    reason: "Profile-slug procedures are account identity management.",
  },
  {
    target: "forwarderManagement.updateProfileSlug",
    reason: "Profile-slug procedures are account identity management.",
  },
  {
    target: "providerManagement.createCredential",
    reason: "Accepts plaintext provider secrets; permanently excluded by policy.",
  },
  {
    target: "providerManagement.replaceCredential",
    reason: "Accepts plaintext provider secrets; permanently excluded by policy.",
  },
  {
    target: "providerManagement.listUsageReport",
    reason: "Overlaps the pageable usage report (provider_usage_page_list).",
  },
  {
    target: "providerManagement.repairExpiredAttempts",
    reason: "Operational accounting repair (admin-operated).",
  },
  { target: "modelApiTokens.create", reason: "Returns the one-time raw token secret." },
  {
    target: "modelApiTokens.updateExternalAccess",
    reason:
      "Human-only external-provider consent: an agent must never raise its own token's egress permission.",
  },
  { target: "cliCredentials.createToken", reason: "Returns the one-time raw token secret." },
  {
    target: "cliCredentials.exchangeDeviceCode",
    reason: "Public device-flow credential exchange; not an MCP surface.",
  },
  {
    target: "cliCredentials.deviceLoginRequest",
    reason: "Browser device-login approval page read; not an MCP surface.",
  },
  {
    target: "cliCredentials.approveDeviceLogin",
    reason:
      "Human-only browser approval of a `wsmp login`: an agent must never grant a CLI credential.",
  },
  {
    target: "relayMetadata.deleteOwn",
    reason: "Audit/history deletion without an agent workflow.",
  },
  { target: "relayMetadata.prune", reason: "Admin-only accounting deletion." },
  {
    target: "settings.getAll",
    reason: "Global application settings read; not model-proxy operation.",
  },
  {
    target: "deploymentFlags",
    reason: "Signed-in product gates. The browser reads them; MCP does not.",
  },
  {
    target: "deploymentFeatures",
    reason: "Admin-only deployment inventory, including keyring status.",
  },
  {
    target: "settings.myNotificationPreferences",
    reason: "Notification settings are excluded from MCP.",
  },
  {
    target: "settings.updateMyNotificationPreferences",
    reason: "Notification settings are excluded from MCP.",
  },
  { target: "settings.update", reason: "Admin-only global settings mutation." },
  { target: "devices.list", reason: "Admin-only device administration." },
  { target: "devices.revoke", reason: "Admin-only device administration." },
  { target: "users.list", reason: "Admin-only account management." },
  { target: "users.invite", reason: "Admin-only account management." },
  { target: "users.setRole", reason: "Admin-only account management." },
  { target: "users.archive", reason: "Admin-only account management." },
  { target: "users.unarchive", reason: "Admin-only account management." },
  { target: "users.remove", reason: "Admin-only account management." },
  { target: "adminObservability.listCliDevices", reason: "Admin-only observability." },
  { target: "adminObservability.listEndpoints", reason: "Admin-only observability." },
  { target: "adminObservability.listModels", reason: "Admin-only observability." },
  { target: "adminObservability.listPools", reason: "Admin-only observability." },
  {
    target: "adminObservability.listRelayMetadataSummaries",
    reason: "Admin-only observability.",
  },
  {
    target: "poolFallbackPreferences.set",
    reason: "Human-only own-key egress consent.",
  },
  { target: "poolFallbackPreferences.clear", reason: "Human-only own-key preference management." },
  {
    target: "poolFallbackPreferences.ownerAggregate",
    reason: "Dashboard aggregate count; MCP reads it through forwarder_pool_fallback_get.",
  },
  {
    target: "poolFallbackPreferences.list",
    reason:
      "Private dashboard preferences; MCP reads one pool through forwarder_pool_fallback_get.",
  },
  {
    target: "providerManagement.setAllowDataCollection",
    reason:
      "Human-only OpenRouter privacy opt-out (D9): an agent must never relax an account's data_collection routing.",
  },
  {
    target: "providerCatalog.search",
    reason:
      "Human-only catalog picker: an outbound OpenRouter catalog fetch that stays out of MCP.",
  },
  {
    target: "providerCatalog.importModel",
    reason: "Human-only catalog import; agents use the confirmed provider model tools.",
  },
  {
    target: "providerCatalog.getPoolExternalEquivalent",
    reason: "Human-only pool external-equivalent picker.",
  },
  {
    target: "providerCatalog.setPoolExternalEquivalent",
    reason: "Human-only pool external-equivalent picker (the owner's BYOK consent).",
  },
  {
    target: "mcpGrants.listMine",
    reason:
      "Human-only MCP grant management (Phase 7): a connected MCP client must not enumerate the user's other authorizations.",
  },
  {
    target: "mcpGrants.revokeMine",
    reason:
      "Human-only MCP grant revocation (Phase 7): only the browser session may kill grant generations.",
  },
  {
    target: "mcpTokens.listMine",
    reason:
      "Human-only MCP personal-token management: a connected MCP client must not enumerate the user's other credentials.",
  },
  {
    target: "mcpTokens.create",
    reason: "Returns the one-time raw MCP personal-token secret; human-only browser session.",
  },
  {
    target: "forwarderManagement.setCliDeviceFeatureGrants",
    reason:
      "Human-only device grants including read-only file consent; requires the CLI read switch and configured roots reports.",
  },
  {
    target: "supervisedCommands.pending",
    reason:
      "Human-only supervised-command awareness: the person, not an agent, answers agent requests.",
  },
  {
    target: "supervisedCommands.submitOutput",
    reason:
      "Human-only output review: an agent must never review or release the output of its own request.",
  },
  {
    target: "mcpTokens.updateMine",
    reason:
      "Human-only MCP personal-token capability edits: a connected MCP client must not widen or narrow its own or other credentials.",
  },
  {
    target: "mcpTokens.revokeMine",
    reason:
      "Human-only MCP personal-token revocation: only the browser session may kill PAT generations.",
  },
];
