/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAuthRouteImport } from './routes/$lang/_auth'
import { Route as LangAdminRouteImport } from './routes/$lang/admin'
import { Route as LangLoginRouteImport } from './routes/$lang/login'
import { Route as LangMcpConsentRouteImport } from './routes/$lang/mcp-consent'
import { Route as LangMcpLoginRouteImport } from './routes/$lang/mcp-login'
import { Route as LangSignupRouteImport } from './routes/$lang/signup'
import { Route as LangVerifyEmailRouteImport } from './routes/$lang/verify-email'
import { Route as LangAuthAppRouteImport } from './routes/$lang/_auth/_app'
import { Route as LangAdminIndexRouteImport } from './routes/$lang/admin/index'
import { Route as LangAdminObservabilityRouteImport } from './routes/$lang/admin/observability'
import { Route as LangAdminSettingsRouteImport } from './routes/$lang/admin/settings'
import { Route as LangAdminUsersRouteImport } from './routes/$lang/admin/users'
import { Route as LangAuthAppAccessRouteImport } from './routes/$lang/_auth/_app/access'
import { Route as LangAuthAppActivityRouteImport } from './routes/$lang/_auth/_app/activity'
import { Route as LangAuthAppModelsRouteImport } from './routes/$lang/_auth/_app/models'
import { Route as LangAuthAppOverviewRouteImport } from './routes/$lang/_auth/_app/overview'
import { Route as LangAuthAppSettingsRouteImport } from './routes/$lang/_auth/_app/settings'
import { Route as LangAuthAppTerminalsRouteImport } from './routes/$lang/_auth/_app/terminals'
import { Route as LangAuthAppTestRouteImport } from './routes/$lang/_auth/_app/test'
import { Route as LangAuthAppWelcomeRouteImport } from './routes/$lang/_auth/_app/welcome'
import { Route as LangAuthAppAccessIndexRouteImport } from './routes/$lang/_auth/_app/access/index'
import { Route as LangAuthAppAccessAgentsRouteImport } from './routes/$lang/_auth/_app/access/agents'
import { Route as LangAuthAppAccessApiKeysRouteImport } from './routes/$lang/_auth/_app/access/api-keys'
import { Route as LangAuthAppAccessContributionsRouteImport } from './routes/$lang/_auth/_app/access/contributions'
import { Route as LangAuthAppAccessSharesRouteImport } from './routes/$lang/_auth/_app/access/shares'
import { Route as LangAuthAppActivityIndexRouteImport } from './routes/$lang/_auth/_app/activity/index'
import { Route as LangAuthAppActivityRequestsRouteImport } from './routes/$lang/_auth/_app/activity/requests'
import { Route as LangAuthAppNodesIndexRouteImport } from './routes/$lang/_auth/_app/nodes/index'
import { Route as LangAuthAppNodesNodeIdRouteImport } from './routes/$lang/_auth/_app/nodes/$nodeId'
import { Route as LangAuthAppPoolsIndexRouteImport } from './routes/$lang/_auth/_app/pools/index'
import { Route as LangAuthAppPoolsPoolIdRouteImport } from './routes/$lang/_auth/_app/pools/$poolId'
import { Route as LangAuthAppProfilesIndexRouteImport } from './routes/$lang/_auth/_app/profiles/index'
import { Route as LangAuthAppProfilesProfileIdRouteImport } from './routes/$lang/_auth/_app/profiles/$profileId'
import { Route as LangAuthAppProvidersIndexRouteImport } from './routes/$lang/_auth/_app/providers/index'
import { Route as LangAuthAppProvidersAccountIdRouteImport } from './routes/$lang/_auth/_app/providers/$accountId'
import { Route as LangAuthAppRuntimesIndexRouteImport } from './routes/$lang/_auth/_app/runtimes/index'
import { Route as LangAuthAppRuntimesRuntimeIdRouteImport } from './routes/$lang/_auth/_app/runtimes/$runtimeId'
import { Route as LangAuthAppRuntimesNewRouteImport } from './routes/$lang/_auth/_app/runtimes/new'
import { Route as LangAuthAppSettingsIndexRouteImport } from './routes/$lang/_auth/_app/settings/index'
import { Route as LangAuthAppSettingsSecurityRouteImport } from './routes/$lang/_auth/_app/settings/security'
import { Route as LangAuthAppPoolsPoolIdIndexRouteImport } from './routes/$lang/_auth/_app/pools/$poolId/index'
import { Route as LangAuthAppPoolsPoolIdAdvancedRouteImport } from './routes/$lang/_auth/_app/pools/$poolId/advanced'
import { Route as LangAuthAppPoolsPoolIdCloudRouteImport } from './routes/$lang/_auth/_app/pools/$poolId/cloud'
import { Route as LangAuthAppPoolsPoolIdMediaRouteImport } from './routes/$lang/_auth/_app/pools/$poolId/media'
import { Route as LangAuthAppPoolsPoolIdRoutingRouteImport } from './routes/$lang/_auth/_app/pools/$poolId/routing'
import { Route as LangAuthAppPoolsPoolIdSharingRouteImport } from './routes/$lang/_auth/_app/pools/$poolId/sharing'
import { Route as LangAuthAppRuntimesRuntimeIdIndexRouteImport } from './routes/$lang/_auth/_app/runtimes/$runtimeId/index'
import { Route as LangAuthAppRuntimesRuntimeIdAdvancedRouteImport } from './routes/$lang/_auth/_app/runtimes/$runtimeId/advanced'
import { Route as LangAuthAppRuntimesRuntimeIdDefinitionRouteImport } from './routes/$lang/_auth/_app/runtimes/$runtimeId/definition'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthRoute = LangAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminRoute = LangAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LangRoute,
} as any)
const LangLoginRoute = LangLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangRoute,
} as any)
const LangMcpConsentRoute = LangMcpConsentRouteImport.update({
  id: '/mcp-consent',
  path: '/mcp-consent',
  getParentRoute: () => LangRoute,
} as any)
const LangMcpLoginRoute = LangMcpLoginRouteImport.update({
  id: '/mcp-login',
  path: '/mcp-login',
  getParentRoute: () => LangRoute,
} as any)
const LangSignupRoute = LangSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LangRoute,
} as any)
const LangVerifyEmailRoute = LangVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthAppRoute = LangAuthAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => LangAuthRoute,
} as any)
const LangAdminIndexRoute = LangAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminObservabilityRoute = LangAdminObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminSettingsRoute = LangAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminUsersRoute = LangAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAuthAppAccessRoute = LangAuthAppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => LangAuthAppRoute,
} as any)
const LangAuthAppActivityRoute = LangAuthAppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => LangAuthAppRoute,
} as any)
const LangAuthAppModelsRoute = LangAuthAppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => LangAuthAppRoute,
} as any)
const LangAuthAppOverviewRoute = LangAuthAppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => LangAuthAppRoute,
} as any)
const LangAuthAppSettingsRoute = LangAuthAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LangAuthAppRoute,
} as any)
const LangAuthAppTerminalsRoute = LangAuthAppTerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => LangAuthAppRoute,
} as any)
const LangAuthAppTestRoute = LangAuthAppTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => LangAuthAppRoute,
} as any)
const LangAuthAppWelcomeRoute = LangAuthAppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => LangAuthAppRoute,
} as any)
const LangAuthAppAccessIndexRoute = LangAuthAppAccessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAuthAppAccessRoute,
} as any)
const LangAuthAppAccessAgentsRoute = LangAuthAppAccessAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LangAuthAppAccessRoute,
} as any)
const LangAuthAppAccessApiKeysRoute =
  LangAuthAppAccessApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => LangAuthAppAccessRoute,
  } as any)
const LangAuthAppAccessContributionsRoute =
  LangAuthAppAccessContributionsRouteImport.update({
    id: '/contributions',
    path: '/contributions',
    getParentRoute: () => LangAuthAppAccessRoute,
  } as any)
const LangAuthAppAccessSharesRoute = LangAuthAppAccessSharesRouteImport.update({
  id: '/shares',
  path: '/shares',
  getParentRoute: () => LangAuthAppAccessRoute,
} as any)
const LangAuthAppActivityIndexRoute =
  LangAuthAppActivityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangAuthAppActivityRoute,
  } as any)
const LangAuthAppActivityRequestsRoute =
  LangAuthAppActivityRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => LangAuthAppActivityRoute,
  } as any)
const LangAuthAppNodesIndexRoute = LangAuthAppNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => LangAuthAppRoute,
} as any)
const LangAuthAppNodesNodeIdRoute = LangAuthAppNodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => LangAuthAppRoute,
} as any)
const LangAuthAppPoolsIndexRoute = LangAuthAppPoolsIndexRouteImport.update({
  id: '/pools/',
  path: '/pools/',
  getParentRoute: () => LangAuthAppRoute,
} as any)
const LangAuthAppPoolsPoolIdRoute = LangAuthAppPoolsPoolIdRouteImport.update({
  id: '/pools/$poolId',
  path: '/pools/$poolId',
  getParentRoute: () => LangAuthAppRoute,
} as any)
const LangAuthAppProfilesIndexRoute =
  LangAuthAppProfilesIndexRouteImport.update({
    id: '/profiles/',
    path: '/profiles/',
    getParentRoute: () => LangAuthAppRoute,
  } as any)
const LangAuthAppProfilesProfileIdRoute =
  LangAuthAppProfilesProfileIdRouteImport.update({
    id: '/profiles/$profileId',
    path: '/profiles/$profileId',
    getParentRoute: () => LangAuthAppRoute,
  } as any)
const LangAuthAppProvidersIndexRoute =
  LangAuthAppProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => LangAuthAppRoute,
  } as any)
const LangAuthAppProvidersAccountIdRoute =
  LangAuthAppProvidersAccountIdRouteImport.update({
    id: '/providers/$accountId',
    path: '/providers/$accountId',
    getParentRoute: () => LangAuthAppRoute,
  } as any)
const LangAuthAppRuntimesIndexRoute =
  LangAuthAppRuntimesIndexRouteImport.update({
    id: '/runtimes/',
    path: '/runtimes/',
    getParentRoute: () => LangAuthAppRoute,
  } as any)
const LangAuthAppRuntimesRuntimeIdRoute =
  LangAuthAppRuntimesRuntimeIdRouteImport.update({
    id: '/runtimes/$runtimeId',
    path: '/runtimes/$runtimeId',
    getParentRoute: () => LangAuthAppRoute,
  } as any)
const LangAuthAppRuntimesNewRoute = LangAuthAppRuntimesNewRouteImport.update({
  id: '/runtimes/new',
  path: '/runtimes/new',
  getParentRoute: () => LangAuthAppRoute,
} as any)
const LangAuthAppSettingsIndexRoute =
  LangAuthAppSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangAuthAppSettingsRoute,
  } as any)
const LangAuthAppSettingsSecurityRoute =
  LangAuthAppSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => LangAuthAppSettingsRoute,
  } as any)
const LangAuthAppPoolsPoolIdIndexRoute =
  LangAuthAppPoolsPoolIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangAuthAppPoolsPoolIdRoute,
  } as any)
const LangAuthAppPoolsPoolIdAdvancedRoute =
  LangAuthAppPoolsPoolIdAdvancedRouteImport.update({
    id: '/advanced',
    path: '/advanced',
    getParentRoute: () => LangAuthAppPoolsPoolIdRoute,
  } as any)
const LangAuthAppPoolsPoolIdCloudRoute =
  LangAuthAppPoolsPoolIdCloudRouteImport.update({
    id: '/cloud',
    path: '/cloud',
    getParentRoute: () => LangAuthAppPoolsPoolIdRoute,
  } as any)
const LangAuthAppPoolsPoolIdMediaRoute =
  LangAuthAppPoolsPoolIdMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => LangAuthAppPoolsPoolIdRoute,
  } as any)
const LangAuthAppPoolsPoolIdRoutingRoute =
  LangAuthAppPoolsPoolIdRoutingRouteImport.update({
    id: '/routing',
    path: '/routing',
    getParentRoute: () => LangAuthAppPoolsPoolIdRoute,
  } as any)
const LangAuthAppPoolsPoolIdSharingRoute =
  LangAuthAppPoolsPoolIdSharingRouteImport.update({
    id: '/sharing',
    path: '/sharing',
    getParentRoute: () => LangAuthAppPoolsPoolIdRoute,
  } as any)
const LangAuthAppRuntimesRuntimeIdIndexRoute =
  LangAuthAppRuntimesRuntimeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangAuthAppRuntimesRuntimeIdRoute,
  } as any)
const LangAuthAppRuntimesRuntimeIdAdvancedRoute =
  LangAuthAppRuntimesRuntimeIdAdvancedRouteImport.update({
    id: '/advanced',
    path: '/advanced',
    getParentRoute: () => LangAuthAppRuntimesRuntimeIdRoute,
  } as any)
const LangAuthAppRuntimesRuntimeIdDefinitionRoute =
  LangAuthAppRuntimesRuntimeIdDefinitionRouteImport.update({
    id: '/definition',
    path: '/definition',
    getParentRoute: () => LangAuthAppRuntimesRuntimeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/admin': typeof LangAdminRouteWithChildren
  '/$lang/login': typeof LangLoginRoute
  '/$lang/mcp-consent': typeof LangMcpConsentRoute
  '/$lang/mcp-login': typeof LangMcpLoginRoute
  '/$lang/signup': typeof LangSignupRoute
  '/$lang/verify-email': typeof LangVerifyEmailRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/observability': typeof LangAdminObservabilityRoute
  '/$lang/admin/settings': typeof LangAdminSettingsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/access': typeof LangAuthAppAccessRouteWithChildren
  '/$lang/activity': typeof LangAuthAppActivityRouteWithChildren
  '/$lang/models': typeof LangAuthAppModelsRoute
  '/$lang/overview': typeof LangAuthAppOverviewRoute
  '/$lang/settings': typeof LangAuthAppSettingsRouteWithChildren
  '/$lang/terminals': typeof LangAuthAppTerminalsRoute
  '/$lang/test': typeof LangAuthAppTestRoute
  '/$lang/welcome': typeof LangAuthAppWelcomeRoute
  '/$lang/access/agents': typeof LangAuthAppAccessAgentsRoute
  '/$lang/access/api-keys': typeof LangAuthAppAccessApiKeysRoute
  '/$lang/access/contributions': typeof LangAuthAppAccessContributionsRoute
  '/$lang/access/shares': typeof LangAuthAppAccessSharesRoute
  '/$lang/activity/requests': typeof LangAuthAppActivityRequestsRoute
  '/$lang/nodes/$nodeId': typeof LangAuthAppNodesNodeIdRoute
  '/$lang/pools/$poolId': typeof LangAuthAppPoolsPoolIdRouteWithChildren
  '/$lang/profiles/$profileId': typeof LangAuthAppProfilesProfileIdRoute
  '/$lang/providers/$accountId': typeof LangAuthAppProvidersAccountIdRoute
  '/$lang/runtimes/$runtimeId': typeof LangAuthAppRuntimesRuntimeIdRouteWithChildren
  '/$lang/runtimes/new': typeof LangAuthAppRuntimesNewRoute
  '/$lang/settings/security': typeof LangAuthAppSettingsSecurityRoute
  '/$lang/access/': typeof LangAuthAppAccessIndexRoute
  '/$lang/activity/': typeof LangAuthAppActivityIndexRoute
  '/$lang/nodes/': typeof LangAuthAppNodesIndexRoute
  '/$lang/pools/': typeof LangAuthAppPoolsIndexRoute
  '/$lang/profiles/': typeof LangAuthAppProfilesIndexRoute
  '/$lang/providers/': typeof LangAuthAppProvidersIndexRoute
  '/$lang/runtimes/': typeof LangAuthAppRuntimesIndexRoute
  '/$lang/settings/': typeof LangAuthAppSettingsIndexRoute
  '/$lang/pools/$poolId/advanced': typeof LangAuthAppPoolsPoolIdAdvancedRoute
  '/$lang/pools/$poolId/cloud': typeof LangAuthAppPoolsPoolIdCloudRoute
  '/$lang/pools/$poolId/media': typeof LangAuthAppPoolsPoolIdMediaRoute
  '/$lang/pools/$poolId/routing': typeof LangAuthAppPoolsPoolIdRoutingRoute
  '/$lang/pools/$poolId/sharing': typeof LangAuthAppPoolsPoolIdSharingRoute
  '/$lang/runtimes/$runtimeId/advanced': typeof LangAuthAppRuntimesRuntimeIdAdvancedRoute
  '/$lang/runtimes/$runtimeId/definition': typeof LangAuthAppRuntimesRuntimeIdDefinitionRoute
  '/$lang/pools/$poolId/': typeof LangAuthAppPoolsPoolIdIndexRoute
  '/$lang/runtimes/$runtimeId/': typeof LangAuthAppRuntimesRuntimeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/mcp-consent': typeof LangMcpConsentRoute
  '/$lang/mcp-login': typeof LangMcpLoginRoute
  '/$lang/signup': typeof LangSignupRoute
  '/$lang/verify-email': typeof LangVerifyEmailRoute
  '/$lang/admin/observability': typeof LangAdminObservabilityRoute
  '/$lang/admin/settings': typeof LangAdminSettingsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/admin': typeof LangAdminIndexRoute
  '/$lang/models': typeof LangAuthAppModelsRoute
  '/$lang/overview': typeof LangAuthAppOverviewRoute
  '/$lang/terminals': typeof LangAuthAppTerminalsRoute
  '/$lang/test': typeof LangAuthAppTestRoute
  '/$lang/welcome': typeof LangAuthAppWelcomeRoute
  '/$lang/access/agents': typeof LangAuthAppAccessAgentsRoute
  '/$lang/access/api-keys': typeof LangAuthAppAccessApiKeysRoute
  '/$lang/access/contributions': typeof LangAuthAppAccessContributionsRoute
  '/$lang/access/shares': typeof LangAuthAppAccessSharesRoute
  '/$lang/activity/requests': typeof LangAuthAppActivityRequestsRoute
  '/$lang/nodes/$nodeId': typeof LangAuthAppNodesNodeIdRoute
  '/$lang/profiles/$profileId': typeof LangAuthAppProfilesProfileIdRoute
  '/$lang/providers/$accountId': typeof LangAuthAppProvidersAccountIdRoute
  '/$lang/runtimes/new': typeof LangAuthAppRuntimesNewRoute
  '/$lang/settings/security': typeof LangAuthAppSettingsSecurityRoute
  '/$lang/access': typeof LangAuthAppAccessIndexRoute
  '/$lang/activity': typeof LangAuthAppActivityIndexRoute
  '/$lang/nodes': typeof LangAuthAppNodesIndexRoute
  '/$lang/pools': typeof LangAuthAppPoolsIndexRoute
  '/$lang/profiles': typeof LangAuthAppProfilesIndexRoute
  '/$lang/providers': typeof LangAuthAppProvidersIndexRoute
  '/$lang/runtimes': typeof LangAuthAppRuntimesIndexRoute
  '/$lang/settings': typeof LangAuthAppSettingsIndexRoute
  '/$lang/pools/$poolId/advanced': typeof LangAuthAppPoolsPoolIdAdvancedRoute
  '/$lang/pools/$poolId/cloud': typeof LangAuthAppPoolsPoolIdCloudRoute
  '/$lang/pools/$poolId/media': typeof LangAuthAppPoolsPoolIdMediaRoute
  '/$lang/pools/$poolId/routing': typeof LangAuthAppPoolsPoolIdRoutingRoute
  '/$lang/pools/$poolId/sharing': typeof LangAuthAppPoolsPoolIdSharingRoute
  '/$lang/runtimes/$runtimeId/advanced': typeof LangAuthAppRuntimesRuntimeIdAdvancedRoute
  '/$lang/runtimes/$runtimeId/definition': typeof LangAuthAppRuntimesRuntimeIdDefinitionRoute
  '/$lang/pools/$poolId': typeof LangAuthAppPoolsPoolIdIndexRoute
  '/$lang/runtimes/$runtimeId': typeof LangAuthAppRuntimesRuntimeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/_auth': typeof LangAuthRouteWithChildren
  '/$lang/admin': typeof LangAdminRouteWithChildren
  '/$lang/login': typeof LangLoginRoute
  '/$lang/mcp-consent': typeof LangMcpConsentRoute
  '/$lang/mcp-login': typeof LangMcpLoginRoute
  '/$lang/signup': typeof LangSignupRoute
  '/$lang/verify-email': typeof LangVerifyEmailRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/_auth/_app': typeof LangAuthAppRouteWithChildren
  '/$lang/admin/observability': typeof LangAdminObservabilityRoute
  '/$lang/admin/settings': typeof LangAdminSettingsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/_auth/_app/access': typeof LangAuthAppAccessRouteWithChildren
  '/$lang/_auth/_app/activity': typeof LangAuthAppActivityRouteWithChildren
  '/$lang/_auth/_app/models': typeof LangAuthAppModelsRoute
  '/$lang/_auth/_app/overview': typeof LangAuthAppOverviewRoute
  '/$lang/_auth/_app/settings': typeof LangAuthAppSettingsRouteWithChildren
  '/$lang/_auth/_app/terminals': typeof LangAuthAppTerminalsRoute
  '/$lang/_auth/_app/test': typeof LangAuthAppTestRoute
  '/$lang/_auth/_app/welcome': typeof LangAuthAppWelcomeRoute
  '/$lang/_auth/_app/access/agents': typeof LangAuthAppAccessAgentsRoute
  '/$lang/_auth/_app/access/api-keys': typeof LangAuthAppAccessApiKeysRoute
  '/$lang/_auth/_app/access/contributions': typeof LangAuthAppAccessContributionsRoute
  '/$lang/_auth/_app/access/shares': typeof LangAuthAppAccessSharesRoute
  '/$lang/_auth/_app/activity/requests': typeof LangAuthAppActivityRequestsRoute
  '/$lang/_auth/_app/nodes/$nodeId': typeof LangAuthAppNodesNodeIdRoute
  '/$lang/_auth/_app/pools/$poolId': typeof LangAuthAppPoolsPoolIdRouteWithChildren
  '/$lang/_auth/_app/profiles/$profileId': typeof LangAuthAppProfilesProfileIdRoute
  '/$lang/_auth/_app/providers/$accountId': typeof LangAuthAppProvidersAccountIdRoute
  '/$lang/_auth/_app/runtimes/$runtimeId': typeof LangAuthAppRuntimesRuntimeIdRouteWithChildren
  '/$lang/_auth/_app/runtimes/new': typeof LangAuthAppRuntimesNewRoute
  '/$lang/_auth/_app/settings/security': typeof LangAuthAppSettingsSecurityRoute
  '/$lang/_auth/_app/access/': typeof LangAuthAppAccessIndexRoute
  '/$lang/_auth/_app/activity/': typeof LangAuthAppActivityIndexRoute
  '/$lang/_auth/_app/nodes/': typeof LangAuthAppNodesIndexRoute
  '/$lang/_auth/_app/pools/': typeof LangAuthAppPoolsIndexRoute
  '/$lang/_auth/_app/profiles/': typeof LangAuthAppProfilesIndexRoute
  '/$lang/_auth/_app/providers/': typeof LangAuthAppProvidersIndexRoute
  '/$lang/_auth/_app/runtimes/': typeof LangAuthAppRuntimesIndexRoute
  '/$lang/_auth/_app/settings/': typeof LangAuthAppSettingsIndexRoute
  '/$lang/_auth/_app/pools/$poolId/advanced': typeof LangAuthAppPoolsPoolIdAdvancedRoute
  '/$lang/_auth/_app/pools/$poolId/cloud': typeof LangAuthAppPoolsPoolIdCloudRoute
  '/$lang/_auth/_app/pools/$poolId/media': typeof LangAuthAppPoolsPoolIdMediaRoute
  '/$lang/_auth/_app/pools/$poolId/routing': typeof LangAuthAppPoolsPoolIdRoutingRoute
  '/$lang/_auth/_app/pools/$poolId/sharing': typeof LangAuthAppPoolsPoolIdSharingRoute
  '/$lang/_auth/_app/runtimes/$runtimeId/advanced': typeof LangAuthAppRuntimesRuntimeIdAdvancedRoute
  '/$lang/_auth/_app/runtimes/$runtimeId/definition': typeof LangAuthAppRuntimesRuntimeIdDefinitionRoute
  '/$lang/_auth/_app/pools/$poolId/': typeof LangAuthAppPoolsPoolIdIndexRoute
  '/$lang/_auth/_app/runtimes/$runtimeId/': typeof LangAuthAppRuntimesRuntimeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/login'
    | '/$lang/mcp-consent'
    | '/$lang/mcp-login'
    | '/$lang/signup'
    | '/$lang/verify-email'
    | '/$lang/'
    | '/$lang/admin/observability'
    | '/$lang/admin/settings'
    | '/$lang/admin/users'
    | '/$lang/admin/'
    | '/$lang/access'
    | '/$lang/activity'
    | '/$lang/models'
    | '/$lang/overview'
    | '/$lang/settings'
    | '/$lang/terminals'
    | '/$lang/test'
    | '/$lang/welcome'
    | '/$lang/access/agents'
    | '/$lang/access/api-keys'
    | '/$lang/access/contributions'
    | '/$lang/access/shares'
    | '/$lang/activity/requests'
    | '/$lang/nodes/$nodeId'
    | '/$lang/pools/$poolId'
    | '/$lang/profiles/$profileId'
    | '/$lang/providers/$accountId'
    | '/$lang/runtimes/$runtimeId'
    | '/$lang/runtimes/new'
    | '/$lang/settings/security'
    | '/$lang/access/'
    | '/$lang/activity/'
    | '/$lang/nodes/'
    | '/$lang/pools/'
    | '/$lang/profiles/'
    | '/$lang/providers/'
    | '/$lang/runtimes/'
    | '/$lang/settings/'
    | '/$lang/pools/$poolId/advanced'
    | '/$lang/pools/$poolId/cloud'
    | '/$lang/pools/$poolId/media'
    | '/$lang/pools/$poolId/routing'
    | '/$lang/pools/$poolId/sharing'
    | '/$lang/runtimes/$runtimeId/advanced'
    | '/$lang/runtimes/$runtimeId/definition'
    | '/$lang/pools/$poolId/'
    | '/$lang/runtimes/$runtimeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/login'
    | '/$lang/mcp-consent'
    | '/$lang/mcp-login'
    | '/$lang/signup'
    | '/$lang/verify-email'
    | '/$lang/admin/observability'
    | '/$lang/admin/settings'
    | '/$lang/admin/users'
    | '/$lang/admin'
    | '/$lang/models'
    | '/$lang/overview'
    | '/$lang/terminals'
    | '/$lang/test'
    | '/$lang/welcome'
    | '/$lang/access/agents'
    | '/$lang/access/api-keys'
    | '/$lang/access/contributions'
    | '/$lang/access/shares'
    | '/$lang/activity/requests'
    | '/$lang/nodes/$nodeId'
    | '/$lang/profiles/$profileId'
    | '/$lang/providers/$accountId'
    | '/$lang/runtimes/new'
    | '/$lang/settings/security'
    | '/$lang/access'
    | '/$lang/activity'
    | '/$lang/nodes'
    | '/$lang/pools'
    | '/$lang/profiles'
    | '/$lang/providers'
    | '/$lang/runtimes'
    | '/$lang/settings'
    | '/$lang/pools/$poolId/advanced'
    | '/$lang/pools/$poolId/cloud'
    | '/$lang/pools/$poolId/media'
    | '/$lang/pools/$poolId/routing'
    | '/$lang/pools/$poolId/sharing'
    | '/$lang/runtimes/$runtimeId/advanced'
    | '/$lang/runtimes/$runtimeId/definition'
    | '/$lang/pools/$poolId'
    | '/$lang/runtimes/$runtimeId'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/_auth'
    | '/$lang/admin'
    | '/$lang/login'
    | '/$lang/mcp-consent'
    | '/$lang/mcp-login'
    | '/$lang/signup'
    | '/$lang/verify-email'
    | '/$lang/'
    | '/$lang/_auth/_app'
    | '/$lang/admin/observability'
    | '/$lang/admin/settings'
    | '/$lang/admin/users'
    | '/$lang/admin/'
    | '/$lang/_auth/_app/access'
    | '/$lang/_auth/_app/activity'
    | '/$lang/_auth/_app/models'
    | '/$lang/_auth/_app/overview'
    | '/$lang/_auth/_app/settings'
    | '/$lang/_auth/_app/terminals'
    | '/$lang/_auth/_app/test'
    | '/$lang/_auth/_app/welcome'
    | '/$lang/_auth/_app/access/agents'
    | '/$lang/_auth/_app/access/api-keys'
    | '/$lang/_auth/_app/access/contributions'
    | '/$lang/_auth/_app/access/shares'
    | '/$lang/_auth/_app/activity/requests'
    | '/$lang/_auth/_app/nodes/$nodeId'
    | '/$lang/_auth/_app/pools/$poolId'
    | '/$lang/_auth/_app/profiles/$profileId'
    | '/$lang/_auth/_app/providers/$accountId'
    | '/$lang/_auth/_app/runtimes/$runtimeId'
    | '/$lang/_auth/_app/runtimes/new'
    | '/$lang/_auth/_app/settings/security'
    | '/$lang/_auth/_app/access/'
    | '/$lang/_auth/_app/activity/'
    | '/$lang/_auth/_app/nodes/'
    | '/$lang/_auth/_app/pools/'
    | '/$lang/_auth/_app/profiles/'
    | '/$lang/_auth/_app/providers/'
    | '/$lang/_auth/_app/runtimes/'
    | '/$lang/_auth/_app/settings/'
    | '/$lang/_auth/_app/pools/$poolId/advanced'
    | '/$lang/_auth/_app/pools/$poolId/cloud'
    | '/$lang/_auth/_app/pools/$poolId/media'
    | '/$lang/_auth/_app/pools/$poolId/routing'
    | '/$lang/_auth/_app/pools/$poolId/sharing'
    | '/$lang/_auth/_app/runtimes/$runtimeId/advanced'
    | '/$lang/_auth/_app/runtimes/$runtimeId/definition'
    | '/$lang/_auth/_app/pools/$poolId/'
    | '/$lang/_auth/_app/runtimes/$runtimeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_auth': {
      id: '/$lang/_auth'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAuthRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin': {
      id: '/$lang/admin'
      path: '/admin'
      fullPath: '/$lang/admin'
      preLoaderRoute: typeof LangAdminRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/login': {
      id: '/$lang/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/mcp-consent': {
      id: '/$lang/mcp-consent'
      path: '/mcp-consent'
      fullPath: '/$lang/mcp-consent'
      preLoaderRoute: typeof LangMcpConsentRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/mcp-login': {
      id: '/$lang/mcp-login'
      path: '/mcp-login'
      fullPath: '/$lang/mcp-login'
      preLoaderRoute: typeof LangMcpLoginRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/signup': {
      id: '/$lang/signup'
      path: '/signup'
      fullPath: '/$lang/signup'
      preLoaderRoute: typeof LangSignupRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/verify-email': {
      id: '/$lang/verify-email'
      path: '/verify-email'
      fullPath: '/$lang/verify-email'
      preLoaderRoute: typeof LangVerifyEmailRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_auth/_app': {
      id: '/$lang/_auth/_app'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAuthAppRouteImport
      parentRoute: typeof LangAuthRoute
    }
    '/$lang/admin/': {
      id: '/$lang/admin/'
      path: '/'
      fullPath: '/$lang/admin/'
      preLoaderRoute: typeof LangAdminIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/observability': {
      id: '/$lang/admin/observability'
      path: '/observability'
      fullPath: '/$lang/admin/observability'
      preLoaderRoute: typeof LangAdminObservabilityRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/settings': {
      id: '/$lang/admin/settings'
      path: '/settings'
      fullPath: '/$lang/admin/settings'
      preLoaderRoute: typeof LangAdminSettingsRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/users': {
      id: '/$lang/admin/users'
      path: '/users'
      fullPath: '/$lang/admin/users'
      preLoaderRoute: typeof LangAdminUsersRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/_auth/_app/access': {
      id: '/$lang/_auth/_app/access'
      path: '/access'
      fullPath: '/$lang/access'
      preLoaderRoute: typeof LangAuthAppAccessRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/activity': {
      id: '/$lang/_auth/_app/activity'
      path: '/activity'
      fullPath: '/$lang/activity'
      preLoaderRoute: typeof LangAuthAppActivityRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/models': {
      id: '/$lang/_auth/_app/models'
      path: '/models'
      fullPath: '/$lang/models'
      preLoaderRoute: typeof LangAuthAppModelsRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/overview': {
      id: '/$lang/_auth/_app/overview'
      path: '/overview'
      fullPath: '/$lang/overview'
      preLoaderRoute: typeof LangAuthAppOverviewRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/settings': {
      id: '/$lang/_auth/_app/settings'
      path: '/settings'
      fullPath: '/$lang/settings'
      preLoaderRoute: typeof LangAuthAppSettingsRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/terminals': {
      id: '/$lang/_auth/_app/terminals'
      path: '/terminals'
      fullPath: '/$lang/terminals'
      preLoaderRoute: typeof LangAuthAppTerminalsRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/test': {
      id: '/$lang/_auth/_app/test'
      path: '/test'
      fullPath: '/$lang/test'
      preLoaderRoute: typeof LangAuthAppTestRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/welcome': {
      id: '/$lang/_auth/_app/welcome'
      path: '/welcome'
      fullPath: '/$lang/welcome'
      preLoaderRoute: typeof LangAuthAppWelcomeRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/access/': {
      id: '/$lang/_auth/_app/access/'
      path: '/'
      fullPath: '/$lang/access/'
      preLoaderRoute: typeof LangAuthAppAccessIndexRouteImport
      parentRoute: typeof LangAuthAppAccessRoute
    }
    '/$lang/_auth/_app/access/agents': {
      id: '/$lang/_auth/_app/access/agents'
      path: '/agents'
      fullPath: '/$lang/access/agents'
      preLoaderRoute: typeof LangAuthAppAccessAgentsRouteImport
      parentRoute: typeof LangAuthAppAccessRoute
    }
    '/$lang/_auth/_app/access/api-keys': {
      id: '/$lang/_auth/_app/access/api-keys'
      path: '/api-keys'
      fullPath: '/$lang/access/api-keys'
      preLoaderRoute: typeof LangAuthAppAccessApiKeysRouteImport
      parentRoute: typeof LangAuthAppAccessRoute
    }
    '/$lang/_auth/_app/access/contributions': {
      id: '/$lang/_auth/_app/access/contributions'
      path: '/contributions'
      fullPath: '/$lang/access/contributions'
      preLoaderRoute: typeof LangAuthAppAccessContributionsRouteImport
      parentRoute: typeof LangAuthAppAccessRoute
    }
    '/$lang/_auth/_app/access/shares': {
      id: '/$lang/_auth/_app/access/shares'
      path: '/shares'
      fullPath: '/$lang/access/shares'
      preLoaderRoute: typeof LangAuthAppAccessSharesRouteImport
      parentRoute: typeof LangAuthAppAccessRoute
    }
    '/$lang/_auth/_app/activity/': {
      id: '/$lang/_auth/_app/activity/'
      path: '/'
      fullPath: '/$lang/activity/'
      preLoaderRoute: typeof LangAuthAppActivityIndexRouteImport
      parentRoute: typeof LangAuthAppActivityRoute
    }
    '/$lang/_auth/_app/activity/requests': {
      id: '/$lang/_auth/_app/activity/requests'
      path: '/requests'
      fullPath: '/$lang/activity/requests'
      preLoaderRoute: typeof LangAuthAppActivityRequestsRouteImport
      parentRoute: typeof LangAuthAppActivityRoute
    }
    '/$lang/_auth/_app/nodes/': {
      id: '/$lang/_auth/_app/nodes/'
      path: '/nodes'
      fullPath: '/$lang/nodes/'
      preLoaderRoute: typeof LangAuthAppNodesIndexRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/nodes/$nodeId': {
      id: '/$lang/_auth/_app/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/$lang/nodes/$nodeId'
      preLoaderRoute: typeof LangAuthAppNodesNodeIdRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/pools/': {
      id: '/$lang/_auth/_app/pools/'
      path: '/pools'
      fullPath: '/$lang/pools/'
      preLoaderRoute: typeof LangAuthAppPoolsIndexRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/pools/$poolId': {
      id: '/$lang/_auth/_app/pools/$poolId'
      path: '/pools/$poolId'
      fullPath: '/$lang/pools/$poolId'
      preLoaderRoute: typeof LangAuthAppPoolsPoolIdRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/profiles/': {
      id: '/$lang/_auth/_app/profiles/'
      path: '/profiles'
      fullPath: '/$lang/profiles/'
      preLoaderRoute: typeof LangAuthAppProfilesIndexRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/profiles/$profileId': {
      id: '/$lang/_auth/_app/profiles/$profileId'
      path: '/profiles/$profileId'
      fullPath: '/$lang/profiles/$profileId'
      preLoaderRoute: typeof LangAuthAppProfilesProfileIdRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/providers/': {
      id: '/$lang/_auth/_app/providers/'
      path: '/providers'
      fullPath: '/$lang/providers/'
      preLoaderRoute: typeof LangAuthAppProvidersIndexRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/providers/$accountId': {
      id: '/$lang/_auth/_app/providers/$accountId'
      path: '/providers/$accountId'
      fullPath: '/$lang/providers/$accountId'
      preLoaderRoute: typeof LangAuthAppProvidersAccountIdRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/runtimes/': {
      id: '/$lang/_auth/_app/runtimes/'
      path: '/runtimes'
      fullPath: '/$lang/runtimes/'
      preLoaderRoute: typeof LangAuthAppRuntimesIndexRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/runtimes/$runtimeId': {
      id: '/$lang/_auth/_app/runtimes/$runtimeId'
      path: '/runtimes/$runtimeId'
      fullPath: '/$lang/runtimes/$runtimeId'
      preLoaderRoute: typeof LangAuthAppRuntimesRuntimeIdRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/runtimes/new': {
      id: '/$lang/_auth/_app/runtimes/new'
      path: '/runtimes/new'
      fullPath: '/$lang/runtimes/new'
      preLoaderRoute: typeof LangAuthAppRuntimesNewRouteImport
      parentRoute: typeof LangAuthAppRoute
    }
    '/$lang/_auth/_app/settings/': {
      id: '/$lang/_auth/_app/settings/'
      path: '/'
      fullPath: '/$lang/settings/'
      preLoaderRoute: typeof LangAuthAppSettingsIndexRouteImport
      parentRoute: typeof LangAuthAppSettingsRoute
    }
    '/$lang/_auth/_app/settings/security': {
      id: '/$lang/_auth/_app/settings/security'
      path: '/security'
      fullPath: '/$lang/settings/security'
      preLoaderRoute: typeof LangAuthAppSettingsSecurityRouteImport
      parentRoute: typeof LangAuthAppSettingsRoute
    }
    '/$lang/_auth/_app/pools/$poolId/': {
      id: '/$lang/_auth/_app/pools/$poolId/'
      path: '/'
      fullPath: '/$lang/pools/$poolId/'
      preLoaderRoute: typeof LangAuthAppPoolsPoolIdIndexRouteImport
      parentRoute: typeof LangAuthAppPoolsPoolIdRoute
    }
    '/$lang/_auth/_app/pools/$poolId/advanced': {
      id: '/$lang/_auth/_app/pools/$poolId/advanced'
      path: '/advanced'
      fullPath: '/$lang/pools/$poolId/advanced'
      preLoaderRoute: typeof LangAuthAppPoolsPoolIdAdvancedRouteImport
      parentRoute: typeof LangAuthAppPoolsPoolIdRoute
    }
    '/$lang/_auth/_app/pools/$poolId/cloud': {
      id: '/$lang/_auth/_app/pools/$poolId/cloud'
      path: '/cloud'
      fullPath: '/$lang/pools/$poolId/cloud'
      preLoaderRoute: typeof LangAuthAppPoolsPoolIdCloudRouteImport
      parentRoute: typeof LangAuthAppPoolsPoolIdRoute
    }
    '/$lang/_auth/_app/pools/$poolId/media': {
      id: '/$lang/_auth/_app/pools/$poolId/media'
      path: '/media'
      fullPath: '/$lang/pools/$poolId/media'
      preLoaderRoute: typeof LangAuthAppPoolsPoolIdMediaRouteImport
      parentRoute: typeof LangAuthAppPoolsPoolIdRoute
    }
    '/$lang/_auth/_app/pools/$poolId/routing': {
      id: '/$lang/_auth/_app/pools/$poolId/routing'
      path: '/routing'
      fullPath: '/$lang/pools/$poolId/routing'
      preLoaderRoute: typeof LangAuthAppPoolsPoolIdRoutingRouteImport
      parentRoute: typeof LangAuthAppPoolsPoolIdRoute
    }
    '/$lang/_auth/_app/pools/$poolId/sharing': {
      id: '/$lang/_auth/_app/pools/$poolId/sharing'
      path: '/sharing'
      fullPath: '/$lang/pools/$poolId/sharing'
      preLoaderRoute: typeof LangAuthAppPoolsPoolIdSharingRouteImport
      parentRoute: typeof LangAuthAppPoolsPoolIdRoute
    }
    '/$lang/_auth/_app/runtimes/$runtimeId/': {
      id: '/$lang/_auth/_app/runtimes/$runtimeId/'
      path: '/'
      fullPath: '/$lang/runtimes/$runtimeId/'
      preLoaderRoute: typeof LangAuthAppRuntimesRuntimeIdIndexRouteImport
      parentRoute: typeof LangAuthAppRuntimesRuntimeIdRoute
    }
    '/$lang/_auth/_app/runtimes/$runtimeId/advanced': {
      id: '/$lang/_auth/_app/runtimes/$runtimeId/advanced'
      path: '/advanced'
      fullPath: '/$lang/runtimes/$runtimeId/advanced'
      preLoaderRoute: typeof LangAuthAppRuntimesRuntimeIdAdvancedRouteImport
      parentRoute: typeof LangAuthAppRuntimesRuntimeIdRoute
    }
    '/$lang/_auth/_app/runtimes/$runtimeId/definition': {
      id: '/$lang/_auth/_app/runtimes/$runtimeId/definition'
      path: '/definition'
      fullPath: '/$lang/runtimes/$runtimeId/definition'
      preLoaderRoute: typeof LangAuthAppRuntimesRuntimeIdDefinitionRouteImport
      parentRoute: typeof LangAuthAppRuntimesRuntimeIdRoute
    }
  }
}

interface LangAuthAppAccessRouteChildren {
  LangAuthAppAccessAgentsRoute: typeof LangAuthAppAccessAgentsRoute
  LangAuthAppAccessApiKeysRoute: typeof LangAuthAppAccessApiKeysRoute
  LangAuthAppAccessContributionsRoute: typeof LangAuthAppAccessContributionsRoute
  LangAuthAppAccessSharesRoute: typeof LangAuthAppAccessSharesRoute
  LangAuthAppAccessIndexRoute: typeof LangAuthAppAccessIndexRoute
}

const LangAuthAppAccessRouteChildren: LangAuthAppAccessRouteChildren = {
  LangAuthAppAccessAgentsRoute: LangAuthAppAccessAgentsRoute,
  LangAuthAppAccessApiKeysRoute: LangAuthAppAccessApiKeysRoute,
  LangAuthAppAccessContributionsRoute: LangAuthAppAccessContributionsRoute,
  LangAuthAppAccessSharesRoute: LangAuthAppAccessSharesRoute,
  LangAuthAppAccessIndexRoute: LangAuthAppAccessIndexRoute,
}

const LangAuthAppAccessRouteWithChildren =
  LangAuthAppAccessRoute._addFileChildren(LangAuthAppAccessRouteChildren)

interface LangAuthAppActivityRouteChildren {
  LangAuthAppActivityRequestsRoute: typeof LangAuthAppActivityRequestsRoute
  LangAuthAppActivityIndexRoute: typeof LangAuthAppActivityIndexRoute
}

const LangAuthAppActivityRouteChildren: LangAuthAppActivityRouteChildren = {
  LangAuthAppActivityRequestsRoute: LangAuthAppActivityRequestsRoute,
  LangAuthAppActivityIndexRoute: LangAuthAppActivityIndexRoute,
}

const LangAuthAppActivityRouteWithChildren =
  LangAuthAppActivityRoute._addFileChildren(LangAuthAppActivityRouteChildren)

interface LangAuthAppSettingsRouteChildren {
  LangAuthAppSettingsSecurityRoute: typeof LangAuthAppSettingsSecurityRoute
  LangAuthAppSettingsIndexRoute: typeof LangAuthAppSettingsIndexRoute
}

const LangAuthAppSettingsRouteChildren: LangAuthAppSettingsRouteChildren = {
  LangAuthAppSettingsSecurityRoute: LangAuthAppSettingsSecurityRoute,
  LangAuthAppSettingsIndexRoute: LangAuthAppSettingsIndexRoute,
}

const LangAuthAppSettingsRouteWithChildren =
  LangAuthAppSettingsRoute._addFileChildren(LangAuthAppSettingsRouteChildren)

interface LangAuthAppPoolsPoolIdRouteChildren {
  LangAuthAppPoolsPoolIdAdvancedRoute: typeof LangAuthAppPoolsPoolIdAdvancedRoute
  LangAuthAppPoolsPoolIdCloudRoute: typeof LangAuthAppPoolsPoolIdCloudRoute
  LangAuthAppPoolsPoolIdMediaRoute: typeof LangAuthAppPoolsPoolIdMediaRoute
  LangAuthAppPoolsPoolIdRoutingRoute: typeof LangAuthAppPoolsPoolIdRoutingRoute
  LangAuthAppPoolsPoolIdSharingRoute: typeof LangAuthAppPoolsPoolIdSharingRoute
  LangAuthAppPoolsPoolIdIndexRoute: typeof LangAuthAppPoolsPoolIdIndexRoute
}

const LangAuthAppPoolsPoolIdRouteChildren: LangAuthAppPoolsPoolIdRouteChildren =
  {
    LangAuthAppPoolsPoolIdAdvancedRoute: LangAuthAppPoolsPoolIdAdvancedRoute,
    LangAuthAppPoolsPoolIdCloudRoute: LangAuthAppPoolsPoolIdCloudRoute,
    LangAuthAppPoolsPoolIdMediaRoute: LangAuthAppPoolsPoolIdMediaRoute,
    LangAuthAppPoolsPoolIdRoutingRoute: LangAuthAppPoolsPoolIdRoutingRoute,
    LangAuthAppPoolsPoolIdSharingRoute: LangAuthAppPoolsPoolIdSharingRoute,
    LangAuthAppPoolsPoolIdIndexRoute: LangAuthAppPoolsPoolIdIndexRoute,
  }

const LangAuthAppPoolsPoolIdRouteWithChildren =
  LangAuthAppPoolsPoolIdRoute._addFileChildren(
    LangAuthAppPoolsPoolIdRouteChildren,
  )

interface LangAuthAppRuntimesRuntimeIdRouteChildren {
  LangAuthAppRuntimesRuntimeIdAdvancedRoute: typeof LangAuthAppRuntimesRuntimeIdAdvancedRoute
  LangAuthAppRuntimesRuntimeIdDefinitionRoute: typeof LangAuthAppRuntimesRuntimeIdDefinitionRoute
  LangAuthAppRuntimesRuntimeIdIndexRoute: typeof LangAuthAppRuntimesRuntimeIdIndexRoute
}

const LangAuthAppRuntimesRuntimeIdRouteChildren: LangAuthAppRuntimesRuntimeIdRouteChildren =
  {
    LangAuthAppRuntimesRuntimeIdAdvancedRoute:
      LangAuthAppRuntimesRuntimeIdAdvancedRoute,
    LangAuthAppRuntimesRuntimeIdDefinitionRoute:
      LangAuthAppRuntimesRuntimeIdDefinitionRoute,
    LangAuthAppRuntimesRuntimeIdIndexRoute:
      LangAuthAppRuntimesRuntimeIdIndexRoute,
  }

const LangAuthAppRuntimesRuntimeIdRouteWithChildren =
  LangAuthAppRuntimesRuntimeIdRoute._addFileChildren(
    LangAuthAppRuntimesRuntimeIdRouteChildren,
  )

interface LangAuthAppRouteChildren {
  LangAuthAppAccessRoute: typeof LangAuthAppAccessRouteWithChildren
  LangAuthAppActivityRoute: typeof LangAuthAppActivityRouteWithChildren
  LangAuthAppModelsRoute: typeof LangAuthAppModelsRoute
  LangAuthAppOverviewRoute: typeof LangAuthAppOverviewRoute
  LangAuthAppSettingsRoute: typeof LangAuthAppSettingsRouteWithChildren
  LangAuthAppTerminalsRoute: typeof LangAuthAppTerminalsRoute
  LangAuthAppTestRoute: typeof LangAuthAppTestRoute
  LangAuthAppWelcomeRoute: typeof LangAuthAppWelcomeRoute
  LangAuthAppNodesNodeIdRoute: typeof LangAuthAppNodesNodeIdRoute
  LangAuthAppPoolsPoolIdRoute: typeof LangAuthAppPoolsPoolIdRouteWithChildren
  LangAuthAppProfilesProfileIdRoute: typeof LangAuthAppProfilesProfileIdRoute
  LangAuthAppProvidersAccountIdRoute: typeof LangAuthAppProvidersAccountIdRoute
  LangAuthAppRuntimesRuntimeIdRoute: typeof LangAuthAppRuntimesRuntimeIdRouteWithChildren
  LangAuthAppRuntimesNewRoute: typeof LangAuthAppRuntimesNewRoute
  LangAuthAppNodesIndexRoute: typeof LangAuthAppNodesIndexRoute
  LangAuthAppPoolsIndexRoute: typeof LangAuthAppPoolsIndexRoute
  LangAuthAppProfilesIndexRoute: typeof LangAuthAppProfilesIndexRoute
  LangAuthAppProvidersIndexRoute: typeof LangAuthAppProvidersIndexRoute
  LangAuthAppRuntimesIndexRoute: typeof LangAuthAppRuntimesIndexRoute
}

const LangAuthAppRouteChildren: LangAuthAppRouteChildren = {
  LangAuthAppAccessRoute: LangAuthAppAccessRouteWithChildren,
  LangAuthAppActivityRoute: LangAuthAppActivityRouteWithChildren,
  LangAuthAppModelsRoute: LangAuthAppModelsRoute,
  LangAuthAppOverviewRoute: LangAuthAppOverviewRoute,
  LangAuthAppSettingsRoute: LangAuthAppSettingsRouteWithChildren,
  LangAuthAppTerminalsRoute: LangAuthAppTerminalsRoute,
  LangAuthAppTestRoute: LangAuthAppTestRoute,
  LangAuthAppWelcomeRoute: LangAuthAppWelcomeRoute,
  LangAuthAppNodesNodeIdRoute: LangAuthAppNodesNodeIdRoute,
  LangAuthAppPoolsPoolIdRoute: LangAuthAppPoolsPoolIdRouteWithChildren,
  LangAuthAppProfilesProfileIdRoute: LangAuthAppProfilesProfileIdRoute,
  LangAuthAppProvidersAccountIdRoute: LangAuthAppProvidersAccountIdRoute,
  LangAuthAppRuntimesRuntimeIdRoute:
    LangAuthAppRuntimesRuntimeIdRouteWithChildren,
  LangAuthAppRuntimesNewRoute: LangAuthAppRuntimesNewRoute,
  LangAuthAppNodesIndexRoute: LangAuthAppNodesIndexRoute,
  LangAuthAppPoolsIndexRoute: LangAuthAppPoolsIndexRoute,
  LangAuthAppProfilesIndexRoute: LangAuthAppProfilesIndexRoute,
  LangAuthAppProvidersIndexRoute: LangAuthAppProvidersIndexRoute,
  LangAuthAppRuntimesIndexRoute: LangAuthAppRuntimesIndexRoute,
}

const LangAuthAppRouteWithChildren = LangAuthAppRoute._addFileChildren(
  LangAuthAppRouteChildren,
)

interface LangAuthRouteChildren {
  LangAuthAppRoute: typeof LangAuthAppRouteWithChildren
}

const LangAuthRouteChildren: LangAuthRouteChildren = {
  LangAuthAppRoute: LangAuthAppRouteWithChildren,
}

const LangAuthRouteWithChildren = LangAuthRoute._addFileChildren(
  LangAuthRouteChildren,
)

interface LangAdminRouteChildren {
  LangAdminObservabilityRoute: typeof LangAdminObservabilityRoute
  LangAdminSettingsRoute: typeof LangAdminSettingsRoute
  LangAdminUsersRoute: typeof LangAdminUsersRoute
  LangAdminIndexRoute: typeof LangAdminIndexRoute
}

const LangAdminRouteChildren: LangAdminRouteChildren = {
  LangAdminObservabilityRoute: LangAdminObservabilityRoute,
  LangAdminSettingsRoute: LangAdminSettingsRoute,
  LangAdminUsersRoute: LangAdminUsersRoute,
  LangAdminIndexRoute: LangAdminIndexRoute,
}

const LangAdminRouteWithChildren = LangAdminRoute._addFileChildren(
  LangAdminRouteChildren,
)

interface LangRouteChildren {
  LangAuthRoute: typeof LangAuthRouteWithChildren
  LangAdminRoute: typeof LangAdminRouteWithChildren
  LangLoginRoute: typeof LangLoginRoute
  LangMcpConsentRoute: typeof LangMcpConsentRoute
  LangMcpLoginRoute: typeof LangMcpLoginRoute
  LangSignupRoute: typeof LangSignupRoute
  LangVerifyEmailRoute: typeof LangVerifyEmailRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAuthRoute: LangAuthRouteWithChildren,
  LangAdminRoute: LangAdminRouteWithChildren,
  LangLoginRoute: LangLoginRoute,
  LangMcpConsentRoute: LangMcpConsentRoute,
  LangMcpLoginRoute: LangMcpLoginRoute,
  LangSignupRoute: LangSignupRoute,
  LangVerifyEmailRoute: LangVerifyEmailRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
