/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangVerifyEmailRouteImport } from './routes/$lang/verify-email'
import { Route as LangSignupRouteImport } from './routes/$lang/signup'
import { Route as LangLoginRouteImport } from './routes/$lang/login'
import { Route as LangDeviceRouteImport } from './routes/$lang/device'
import { Route as LangAdminRouteImport } from './routes/$lang/admin'
import { Route as LangAuthRouteImport } from './routes/$lang/_auth'
import { Route as LangAdminIndexRouteImport } from './routes/$lang/admin/index'
import { Route as LangAdminUsersRouteImport } from './routes/$lang/admin/users'
import { Route as LangAdminSettingsRouteImport } from './routes/$lang/admin/settings'
import { Route as LangAdminSeedRouteImport } from './routes/$lang/admin/seed'
import { Route as LangAdminObservabilityRouteImport } from './routes/$lang/admin/observability'
import { Route as LangAdminDevicesRouteImport } from './routes/$lang/admin/devices'
import { Route as LangAuthSettingsRouteImport } from './routes/$lang/_auth/settings'
import { Route as LangAuthDashboardRouteImport } from './routes/$lang/_auth/dashboard'
import { Route as LangAuthSettingsIndexRouteImport } from './routes/$lang/_auth/settings/index'
import { Route as LangAuthDashboardIndexRouteImport } from './routes/$lang/_auth/dashboard/index'
import { Route as LangAuthSettingsSecurityRouteImport } from './routes/$lang/_auth/settings/security'
import { Route as LangAuthDashboardRelayMetadataRouteImport } from './routes/$lang/_auth/dashboard/relay-metadata'
import { Route as LangAuthDashboardPoolsRouteImport } from './routes/$lang/_auth/dashboard/pools'
import { Route as LangAuthDashboardModelApiTokensRouteImport } from './routes/$lang/_auth/dashboard/model-api-tokens'
import { Route as LangAuthDashboardClisRouteImport } from './routes/$lang/_auth/dashboard/clis'
import { Route as LangAuthDashboardCliTokensRouteImport } from './routes/$lang/_auth/dashboard/cli-tokens'
import { Route as LangAuthDashboardChatTestRouteImport } from './routes/$lang/_auth/dashboard/chat-test'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangVerifyEmailRoute = LangVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => LangRoute,
} as any)
const LangSignupRoute = LangSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LangRoute,
} as any)
const LangLoginRoute = LangLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangRoute,
} as any)
const LangDeviceRoute = LangDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminRoute = LangAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthRoute = LangAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminIndexRoute = LangAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminUsersRoute = LangAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminSettingsRoute = LangAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminSeedRoute = LangAdminSeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminObservabilityRoute = LangAdminObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminDevicesRoute = LangAdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAuthSettingsRoute = LangAuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LangAuthRoute,
} as any)
const LangAuthDashboardRoute = LangAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LangAuthRoute,
} as any)
const LangAuthSettingsIndexRoute = LangAuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAuthSettingsRoute,
} as any)
const LangAuthDashboardIndexRoute = LangAuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAuthDashboardRoute,
} as any)
const LangAuthSettingsSecurityRoute =
  LangAuthSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => LangAuthSettingsRoute,
  } as any)
const LangAuthDashboardRelayMetadataRoute =
  LangAuthDashboardRelayMetadataRouteImport.update({
    id: '/relay-metadata',
    path: '/relay-metadata',
    getParentRoute: () => LangAuthDashboardRoute,
  } as any)
const LangAuthDashboardPoolsRoute = LangAuthDashboardPoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => LangAuthDashboardRoute,
} as any)
const LangAuthDashboardModelApiTokensRoute =
  LangAuthDashboardModelApiTokensRouteImport.update({
    id: '/model-api-tokens',
    path: '/model-api-tokens',
    getParentRoute: () => LangAuthDashboardRoute,
  } as any)
const LangAuthDashboardClisRoute = LangAuthDashboardClisRouteImport.update({
  id: '/clis',
  path: '/clis',
  getParentRoute: () => LangAuthDashboardRoute,
} as any)
const LangAuthDashboardCliTokensRoute =
  LangAuthDashboardCliTokensRouteImport.update({
    id: '/cli-tokens',
    path: '/cli-tokens',
    getParentRoute: () => LangAuthDashboardRoute,
  } as any)
const LangAuthDashboardChatTestRoute =
  LangAuthDashboardChatTestRouteImport.update({
    id: '/chat-test',
    path: '/chat-test',
    getParentRoute: () => LangAuthDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/admin': typeof LangAdminRouteWithChildren
  '/$lang/device': typeof LangDeviceRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/signup': typeof LangSignupRoute
  '/$lang/verify-email': typeof LangVerifyEmailRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/dashboard': typeof LangAuthDashboardRouteWithChildren
  '/$lang/settings': typeof LangAuthSettingsRouteWithChildren
  '/$lang/admin/devices': typeof LangAdminDevicesRoute
  '/$lang/admin/observability': typeof LangAdminObservabilityRoute
  '/$lang/admin/seed': typeof LangAdminSeedRoute
  '/$lang/admin/settings': typeof LangAdminSettingsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/dashboard/chat-test': typeof LangAuthDashboardChatTestRoute
  '/$lang/dashboard/cli-tokens': typeof LangAuthDashboardCliTokensRoute
  '/$lang/dashboard/clis': typeof LangAuthDashboardClisRoute
  '/$lang/dashboard/model-api-tokens': typeof LangAuthDashboardModelApiTokensRoute
  '/$lang/dashboard/pools': typeof LangAuthDashboardPoolsRoute
  '/$lang/dashboard/relay-metadata': typeof LangAuthDashboardRelayMetadataRoute
  '/$lang/settings/security': typeof LangAuthSettingsSecurityRoute
  '/$lang/dashboard/': typeof LangAuthDashboardIndexRoute
  '/$lang/settings/': typeof LangAuthSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/device': typeof LangDeviceRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/signup': typeof LangSignupRoute
  '/$lang/verify-email': typeof LangVerifyEmailRoute
  '/$lang/admin/devices': typeof LangAdminDevicesRoute
  '/$lang/admin/observability': typeof LangAdminObservabilityRoute
  '/$lang/admin/seed': typeof LangAdminSeedRoute
  '/$lang/admin/settings': typeof LangAdminSettingsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/admin': typeof LangAdminIndexRoute
  '/$lang/dashboard/chat-test': typeof LangAuthDashboardChatTestRoute
  '/$lang/dashboard/cli-tokens': typeof LangAuthDashboardCliTokensRoute
  '/$lang/dashboard/clis': typeof LangAuthDashboardClisRoute
  '/$lang/dashboard/model-api-tokens': typeof LangAuthDashboardModelApiTokensRoute
  '/$lang/dashboard/pools': typeof LangAuthDashboardPoolsRoute
  '/$lang/dashboard/relay-metadata': typeof LangAuthDashboardRelayMetadataRoute
  '/$lang/settings/security': typeof LangAuthSettingsSecurityRoute
  '/$lang/dashboard': typeof LangAuthDashboardIndexRoute
  '/$lang/settings': typeof LangAuthSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/_auth': typeof LangAuthRouteWithChildren
  '/$lang/admin': typeof LangAdminRouteWithChildren
  '/$lang/device': typeof LangDeviceRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/signup': typeof LangSignupRoute
  '/$lang/verify-email': typeof LangVerifyEmailRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/_auth/dashboard': typeof LangAuthDashboardRouteWithChildren
  '/$lang/_auth/settings': typeof LangAuthSettingsRouteWithChildren
  '/$lang/admin/devices': typeof LangAdminDevicesRoute
  '/$lang/admin/observability': typeof LangAdminObservabilityRoute
  '/$lang/admin/seed': typeof LangAdminSeedRoute
  '/$lang/admin/settings': typeof LangAdminSettingsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/_auth/dashboard/chat-test': typeof LangAuthDashboardChatTestRoute
  '/$lang/_auth/dashboard/cli-tokens': typeof LangAuthDashboardCliTokensRoute
  '/$lang/_auth/dashboard/clis': typeof LangAuthDashboardClisRoute
  '/$lang/_auth/dashboard/model-api-tokens': typeof LangAuthDashboardModelApiTokensRoute
  '/$lang/_auth/dashboard/pools': typeof LangAuthDashboardPoolsRoute
  '/$lang/_auth/dashboard/relay-metadata': typeof LangAuthDashboardRelayMetadataRoute
  '/$lang/_auth/settings/security': typeof LangAuthSettingsSecurityRoute
  '/$lang/_auth/dashboard/': typeof LangAuthDashboardIndexRoute
  '/$lang/_auth/settings/': typeof LangAuthSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/device'
    | '/$lang/login'
    | '/$lang/signup'
    | '/$lang/verify-email'
    | '/$lang/'
    | '/$lang/dashboard'
    | '/$lang/settings'
    | '/$lang/admin/devices'
    | '/$lang/admin/observability'
    | '/$lang/admin/seed'
    | '/$lang/admin/settings'
    | '/$lang/admin/users'
    | '/$lang/admin/'
    | '/$lang/dashboard/chat-test'
    | '/$lang/dashboard/cli-tokens'
    | '/$lang/dashboard/clis'
    | '/$lang/dashboard/model-api-tokens'
    | '/$lang/dashboard/pools'
    | '/$lang/dashboard/relay-metadata'
    | '/$lang/settings/security'
    | '/$lang/dashboard/'
    | '/$lang/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/device'
    | '/$lang/login'
    | '/$lang/signup'
    | '/$lang/verify-email'
    | '/$lang/admin/devices'
    | '/$lang/admin/observability'
    | '/$lang/admin/seed'
    | '/$lang/admin/settings'
    | '/$lang/admin/users'
    | '/$lang/admin'
    | '/$lang/dashboard/chat-test'
    | '/$lang/dashboard/cli-tokens'
    | '/$lang/dashboard/clis'
    | '/$lang/dashboard/model-api-tokens'
    | '/$lang/dashboard/pools'
    | '/$lang/dashboard/relay-metadata'
    | '/$lang/settings/security'
    | '/$lang/dashboard'
    | '/$lang/settings'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/_auth'
    | '/$lang/admin'
    | '/$lang/device'
    | '/$lang/login'
    | '/$lang/signup'
    | '/$lang/verify-email'
    | '/$lang/'
    | '/$lang/_auth/dashboard'
    | '/$lang/_auth/settings'
    | '/$lang/admin/devices'
    | '/$lang/admin/observability'
    | '/$lang/admin/seed'
    | '/$lang/admin/settings'
    | '/$lang/admin/users'
    | '/$lang/admin/'
    | '/$lang/_auth/dashboard/chat-test'
    | '/$lang/_auth/dashboard/cli-tokens'
    | '/$lang/_auth/dashboard/clis'
    | '/$lang/_auth/dashboard/model-api-tokens'
    | '/$lang/_auth/dashboard/pools'
    | '/$lang/_auth/dashboard/relay-metadata'
    | '/$lang/_auth/settings/security'
    | '/$lang/_auth/dashboard/'
    | '/$lang/_auth/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/verify-email': {
      id: '/$lang/verify-email'
      path: '/verify-email'
      fullPath: '/$lang/verify-email'
      preLoaderRoute: typeof LangVerifyEmailRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/signup': {
      id: '/$lang/signup'
      path: '/signup'
      fullPath: '/$lang/signup'
      preLoaderRoute: typeof LangSignupRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/login': {
      id: '/$lang/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/device': {
      id: '/$lang/device'
      path: '/device'
      fullPath: '/$lang/device'
      preLoaderRoute: typeof LangDeviceRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin': {
      id: '/$lang/admin'
      path: '/admin'
      fullPath: '/$lang/admin'
      preLoaderRoute: typeof LangAdminRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_auth': {
      id: '/$lang/_auth'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAuthRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/': {
      id: '/$lang/admin/'
      path: '/'
      fullPath: '/$lang/admin/'
      preLoaderRoute: typeof LangAdminIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/users': {
      id: '/$lang/admin/users'
      path: '/users'
      fullPath: '/$lang/admin/users'
      preLoaderRoute: typeof LangAdminUsersRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/settings': {
      id: '/$lang/admin/settings'
      path: '/settings'
      fullPath: '/$lang/admin/settings'
      preLoaderRoute: typeof LangAdminSettingsRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/seed': {
      id: '/$lang/admin/seed'
      path: '/seed'
      fullPath: '/$lang/admin/seed'
      preLoaderRoute: typeof LangAdminSeedRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/observability': {
      id: '/$lang/admin/observability'
      path: '/observability'
      fullPath: '/$lang/admin/observability'
      preLoaderRoute: typeof LangAdminObservabilityRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/devices': {
      id: '/$lang/admin/devices'
      path: '/devices'
      fullPath: '/$lang/admin/devices'
      preLoaderRoute: typeof LangAdminDevicesRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/_auth/settings': {
      id: '/$lang/_auth/settings'
      path: '/settings'
      fullPath: '/$lang/settings'
      preLoaderRoute: typeof LangAuthSettingsRouteImport
      parentRoute: typeof LangAuthRoute
    }
    '/$lang/_auth/dashboard': {
      id: '/$lang/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof LangAuthDashboardRouteImport
      parentRoute: typeof LangAuthRoute
    }
    '/$lang/_auth/settings/': {
      id: '/$lang/_auth/settings/'
      path: '/'
      fullPath: '/$lang/settings/'
      preLoaderRoute: typeof LangAuthSettingsIndexRouteImport
      parentRoute: typeof LangAuthSettingsRoute
    }
    '/$lang/_auth/dashboard/': {
      id: '/$lang/_auth/dashboard/'
      path: '/'
      fullPath: '/$lang/dashboard/'
      preLoaderRoute: typeof LangAuthDashboardIndexRouteImport
      parentRoute: typeof LangAuthDashboardRoute
    }
    '/$lang/_auth/settings/security': {
      id: '/$lang/_auth/settings/security'
      path: '/security'
      fullPath: '/$lang/settings/security'
      preLoaderRoute: typeof LangAuthSettingsSecurityRouteImport
      parentRoute: typeof LangAuthSettingsRoute
    }
    '/$lang/_auth/dashboard/relay-metadata': {
      id: '/$lang/_auth/dashboard/relay-metadata'
      path: '/relay-metadata'
      fullPath: '/$lang/dashboard/relay-metadata'
      preLoaderRoute: typeof LangAuthDashboardRelayMetadataRouteImport
      parentRoute: typeof LangAuthDashboardRoute
    }
    '/$lang/_auth/dashboard/pools': {
      id: '/$lang/_auth/dashboard/pools'
      path: '/pools'
      fullPath: '/$lang/dashboard/pools'
      preLoaderRoute: typeof LangAuthDashboardPoolsRouteImport
      parentRoute: typeof LangAuthDashboardRoute
    }
    '/$lang/_auth/dashboard/model-api-tokens': {
      id: '/$lang/_auth/dashboard/model-api-tokens'
      path: '/model-api-tokens'
      fullPath: '/$lang/dashboard/model-api-tokens'
      preLoaderRoute: typeof LangAuthDashboardModelApiTokensRouteImport
      parentRoute: typeof LangAuthDashboardRoute
    }
    '/$lang/_auth/dashboard/clis': {
      id: '/$lang/_auth/dashboard/clis'
      path: '/clis'
      fullPath: '/$lang/dashboard/clis'
      preLoaderRoute: typeof LangAuthDashboardClisRouteImport
      parentRoute: typeof LangAuthDashboardRoute
    }
    '/$lang/_auth/dashboard/cli-tokens': {
      id: '/$lang/_auth/dashboard/cli-tokens'
      path: '/cli-tokens'
      fullPath: '/$lang/dashboard/cli-tokens'
      preLoaderRoute: typeof LangAuthDashboardCliTokensRouteImport
      parentRoute: typeof LangAuthDashboardRoute
    }
    '/$lang/_auth/dashboard/chat-test': {
      id: '/$lang/_auth/dashboard/chat-test'
      path: '/chat-test'
      fullPath: '/$lang/dashboard/chat-test'
      preLoaderRoute: typeof LangAuthDashboardChatTestRouteImport
      parentRoute: typeof LangAuthDashboardRoute
    }
  }
}

interface LangAuthDashboardRouteChildren {
  LangAuthDashboardChatTestRoute: typeof LangAuthDashboardChatTestRoute
  LangAuthDashboardCliTokensRoute: typeof LangAuthDashboardCliTokensRoute
  LangAuthDashboardClisRoute: typeof LangAuthDashboardClisRoute
  LangAuthDashboardModelApiTokensRoute: typeof LangAuthDashboardModelApiTokensRoute
  LangAuthDashboardPoolsRoute: typeof LangAuthDashboardPoolsRoute
  LangAuthDashboardRelayMetadataRoute: typeof LangAuthDashboardRelayMetadataRoute
  LangAuthDashboardIndexRoute: typeof LangAuthDashboardIndexRoute
}

const LangAuthDashboardRouteChildren: LangAuthDashboardRouteChildren = {
  LangAuthDashboardChatTestRoute: LangAuthDashboardChatTestRoute,
  LangAuthDashboardCliTokensRoute: LangAuthDashboardCliTokensRoute,
  LangAuthDashboardClisRoute: LangAuthDashboardClisRoute,
  LangAuthDashboardModelApiTokensRoute: LangAuthDashboardModelApiTokensRoute,
  LangAuthDashboardPoolsRoute: LangAuthDashboardPoolsRoute,
  LangAuthDashboardRelayMetadataRoute: LangAuthDashboardRelayMetadataRoute,
  LangAuthDashboardIndexRoute: LangAuthDashboardIndexRoute,
}

const LangAuthDashboardRouteWithChildren =
  LangAuthDashboardRoute._addFileChildren(LangAuthDashboardRouteChildren)

interface LangAuthSettingsRouteChildren {
  LangAuthSettingsSecurityRoute: typeof LangAuthSettingsSecurityRoute
  LangAuthSettingsIndexRoute: typeof LangAuthSettingsIndexRoute
}

const LangAuthSettingsRouteChildren: LangAuthSettingsRouteChildren = {
  LangAuthSettingsSecurityRoute: LangAuthSettingsSecurityRoute,
  LangAuthSettingsIndexRoute: LangAuthSettingsIndexRoute,
}

const LangAuthSettingsRouteWithChildren =
  LangAuthSettingsRoute._addFileChildren(LangAuthSettingsRouteChildren)

interface LangAuthRouteChildren {
  LangAuthDashboardRoute: typeof LangAuthDashboardRouteWithChildren
  LangAuthSettingsRoute: typeof LangAuthSettingsRouteWithChildren
}

const LangAuthRouteChildren: LangAuthRouteChildren = {
  LangAuthDashboardRoute: LangAuthDashboardRouteWithChildren,
  LangAuthSettingsRoute: LangAuthSettingsRouteWithChildren,
}

const LangAuthRouteWithChildren = LangAuthRoute._addFileChildren(
  LangAuthRouteChildren,
)

interface LangAdminRouteChildren {
  LangAdminDevicesRoute: typeof LangAdminDevicesRoute
  LangAdminObservabilityRoute: typeof LangAdminObservabilityRoute
  LangAdminSeedRoute: typeof LangAdminSeedRoute
  LangAdminSettingsRoute: typeof LangAdminSettingsRoute
  LangAdminUsersRoute: typeof LangAdminUsersRoute
  LangAdminIndexRoute: typeof LangAdminIndexRoute
}

const LangAdminRouteChildren: LangAdminRouteChildren = {
  LangAdminDevicesRoute: LangAdminDevicesRoute,
  LangAdminObservabilityRoute: LangAdminObservabilityRoute,
  LangAdminSeedRoute: LangAdminSeedRoute,
  LangAdminSettingsRoute: LangAdminSettingsRoute,
  LangAdminUsersRoute: LangAdminUsersRoute,
  LangAdminIndexRoute: LangAdminIndexRoute,
}

const LangAdminRouteWithChildren = LangAdminRoute._addFileChildren(
  LangAdminRouteChildren,
)

interface LangRouteChildren {
  LangAuthRoute: typeof LangAuthRouteWithChildren
  LangAdminRoute: typeof LangAdminRouteWithChildren
  LangDeviceRoute: typeof LangDeviceRoute
  LangLoginRoute: typeof LangLoginRoute
  LangSignupRoute: typeof LangSignupRoute
  LangVerifyEmailRoute: typeof LangVerifyEmailRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAuthRoute: LangAuthRouteWithChildren,
  LangAdminRoute: LangAdminRouteWithChildren,
  LangDeviceRoute: LangDeviceRoute,
  LangLoginRoute: LangLoginRoute,
  LangSignupRoute: LangSignupRoute,
  LangVerifyEmailRoute: LangVerifyEmailRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
