import { RUNTIME_SLUG_PATTERN } from "@ws-model-proxy/api/lib/runtime-spec";
import {
  REALTIME_MAX_ITEM_SECONDS_MAX,
  REALTIME_MAX_ITEM_SECONDS_MIN,
  REALTIME_SEGMENTED_MAX_ITEM_SECONDS_MAX,
  REALTIME_TRANSCRIPTION_ADAPTERS,
} from "@ws-model-proxy/api/lib/transcription-profile";
import { RESERVED_FORWARDER_SLUGS } from "@ws-model-proxy/config/forwarder-identifiers";
import { z } from "zod";
import { relayFailureSchema } from "./relay-failure.js";

/**
 * Relay 3.0 live speech-to-text frames (`stt.*`, kept from 2.4 with `endpointSlug` renamed
 * `handle`). A server opens a session on one runtime (by its handle) whose served model advertises
 * `audio.transcriptions.realtime`, streams raw PCM to it and receives
 * normalized transcription events. Neither side ever sees engine or OpenAI
 * event JSON: the CLI adapter owns engine quirks, the server owns the client
 * protocol.
 *
 * The Rust mirror is `apps/cli/src/stt_wire.rs`. The shared goldens are
 * `apps/cli/tests/fixtures/relay-3.0/stt/stt-frames.json` (server to node,
 * generated by `stt-protocol.test.ts`) and `stt-events.json` (CLI to server,
 * generated by the Rust tests).
 *
 * Wire shape:
 * - S->C `stt.open {sessionId, handle, upstreamModel, adapter, config, maxItemSeconds,
 *   maxSessionMs, audioWindowBytes}`; `stt.update {sessionId, config}` (applies to the next
 *   item); `stt.commit {sessionId, itemSeq}`; `stt.clear {sessionId, itemSeq}`;
 *   `stt.close {sessionId, reason}`.
 * - S->C binary `stt.audio {sessionId, seq}`: raw PCM s16le, 24 kHz mono, an even number of
 *   bytes, at most {@link STT_AUDIO_FRAME_MAX_BYTES}; `seq` strictly increases per session.
 * - C->S `stt.opened {sessionId}`; `stt.audio.ack {sessionId, bytes}` (byte credits returned
 *   once audio reaches the engine); `stt.event {sessionId, event}`; `stt.error {sessionId,
 *   failure, message?}` (terminal, before or after open); `stt.closed {sessionId}`.
 *
 * Text limits are UTF-8 bytes on both sides, so TypeScript and Rust count alike.
 */

/** One audio frame: about 0.34 s of 24 kHz s16 mono, small for low latency. */

/** The node refuses these names (`apps/cli/src/slug.rs`), so the server never sends one. */
const RESERVED_HANDLES: ReadonlySet<string> = new Set(RESERVED_FORWARDER_SLUGS);

/** The runtime slug (always-on) or instance handle (`i-<id12>`) an `stt.open` names. */
export const sttHandleSchema = z
  .string()
  .regex(RUNTIME_SLUG_PATTERN)
  .refine((handle) => !RESERVED_HANDLES.has(handle), "Reserved name.");

export const STT_AUDIO_FRAME_MAX_BYTES = 32 * 1024;
/** Bounds of the per-session audio credit window the server grants in `stt.open`. */
const STT_AUDIO_WINDOW_MIN_BYTES = STT_AUDIO_FRAME_MAX_BYTES;
export const STT_AUDIO_WINDOW_MAX_BYTES = 1024 * 1024;
export const STT_MAX_SESSION_MS_MIN = 1_000;
export const STT_MAX_SESSION_MS_MAX = 60 * 60 * 1_000;
export const STT_MODEL_MAX_BYTES = 256;
export const STT_PROMPT_MAX_BYTES = 4096;
/** A delta longer than this is split by the CLI. */
export const STT_DELTA_TEXT_MAX_BYTES = 16 * 1024;
/** A transcript longer than this fails the item (`transcript_too_large`). */
export const STT_COMPLETED_TEXT_MAX_BYTES = 48 * 1024;
export const STT_MESSAGE_MAX_BYTES = 512;
export const STT_ITEM_SEQ_MAX = 0xffff_ffff;
export const STT_TOKEN_COUNT_MAX = 1_000_000_000_000;

const encoder = new TextEncoder();
function utf8Bytes(value: string): number {
  return encoder.encode(value).byteLength;
}
/** Well-formed text of at most `max` UTF-8 bytes (`min` bytes or more). */
function wireText(max: number, min = 0) {
  return z.string().refine((value) => {
    if (!value.isWellFormed()) return false;
    const bytes = utf8Bytes(value);
    return bytes >= min && bytes <= max;
  }, `Expected well-formed text of ${min} to ${max} UTF-8 bytes.`);
}

/** 16 raw bytes as canonical unpadded base64url (22 chars, zero trailing bits). */
export function isCanonicalBase64Url16(value: string): boolean {
  return /^[A-Za-z0-9_-]{21}[AQgw]$/.test(value);
}

export const sttSessionIdSchema = z
  .string()
  .refine(isCanonicalBase64Url16, { message: "Expected 16 bytes of canonical base64url." });
const itemSeqSchema = z.number().int().min(0).max(STT_ITEM_SEQ_MAX);

/** Per-item options; the vLLM adapter ignores both (it has neither). */
export const sttConfigSchema = z
  .object({
    language: z
      .string()
      .regex(/^[A-Za-z0-9_.+/-]{1,64}$/)
      .optional(),
    prompt: wireText(STT_PROMPT_MAX_BYTES).optional(),
  })
  .strict();
export type SttConfig = z.infer<typeof sttConfigSchema>;

export const sttOpenSchema = z
  .object({
    type: z.literal("stt.open"),
    sessionId: sttSessionIdSchema,
    /** The runtime slug (always-on) or instance handle (`i-<id12>`). */
    handle: sttHandleSchema,
    upstreamModel: wireText(STT_MODEL_MAX_BYTES, 1).refine((model) => !model.includes("\0")),
    adapter: z.enum(REALTIME_TRANSCRIPTION_ADAPTERS),
    config: sttConfigSchema,
    maxItemSeconds: z
      .number()
      .int()
      .min(REALTIME_MAX_ITEM_SECONDS_MIN)
      .max(REALTIME_MAX_ITEM_SECONDS_MAX),
    maxSessionMs: z.number().int().min(STT_MAX_SESSION_MS_MIN).max(STT_MAX_SESSION_MS_MAX),
    audioWindowBytes: z
      .number()
      .int()
      .min(STT_AUDIO_WINDOW_MIN_BYTES)
      .max(STT_AUDIO_WINDOW_MAX_BYTES)
      .refine((bytes) => bytes % 2 === 0, "The audio window holds whole samples."),
  })
  .strict()
  .refine(
    (open) =>
      open.adapter !== "segmented" ||
      open.maxItemSeconds <= REALTIME_SEGMENTED_MAX_ITEM_SECONDS_MAX,
    "The segmented adapter allows at most 120 seconds per item.",
  );

export const sttServerControlSchema = z.union([
  sttOpenSchema,
  z
    .object({
      type: z.literal("stt.update"),
      sessionId: sttSessionIdSchema,
      config: sttConfigSchema,
    })
    .strict(),
  z
    .object({
      type: z.literal("stt.commit"),
      sessionId: sttSessionIdSchema,
      itemSeq: itemSeqSchema,
    })
    .strict(),
  z
    .object({ type: z.literal("stt.clear"), sessionId: sttSessionIdSchema, itemSeq: itemSeqSchema })
    .strict(),
  z
    .object({
      type: z.literal("stt.close"),
      sessionId: sttSessionIdSchema,
      reason: relayFailureSchema,
    })
    .strict(),
]);
export type SttServerControlMessage = z.infer<typeof sttServerControlSchema>;

const tokenCountSchema = z.number().int().min(0).max(STT_TOKEN_COUNT_MAX);
export const sttEventSchema = z.discriminatedUnion("kind", [
  z
    .object({
      kind: z.literal("delta"),
      itemSeq: itemSeqSchema,
      text: wireText(STT_DELTA_TEXT_MAX_BYTES),
    })
    .strict(),
  z
    .object({
      kind: z.literal("completed"),
      itemSeq: itemSeqSchema,
      text: wireText(STT_COMPLETED_TEXT_MAX_BYTES),
      engineUsage: z
        .object({
          inputTokens: tokenCountSchema.optional(),
          outputTokens: tokenCountSchema.optional(),
        })
        .strict()
        .optional(),
    })
    .strict(),
  z
    .object({
      kind: z.literal("failed"),
      itemSeq: itemSeqSchema,
      code: z.string().regex(/^[a-z0-9_]{1,64}$/),
      message: wireText(STT_MESSAGE_MAX_BYTES),
    })
    .strict(),
  /** The `maxItemSeconds` valve ended the open item. */
  z.object({ kind: z.literal("auto_committed"), itemSeq: itemSeqSchema }).strict(),
]);
export type SttEvent = z.infer<typeof sttEventSchema>;

/** CLI to server; members of `relayClientControlMessageSchema`. */
export const sttClientControlSchemas = [
  z.object({ type: z.literal("stt.opened"), sessionId: sttSessionIdSchema }).strict(),
  z
    .object({
      type: z.literal("stt.audio.ack"),
      sessionId: sttSessionIdSchema,
      bytes: z.number().int().min(1).max(STT_AUDIO_WINDOW_MAX_BYTES),
    })
    .strict(),
  z
    .object({ type: z.literal("stt.event"), sessionId: sttSessionIdSchema, event: sttEventSchema })
    .strict(),
  z
    .object({
      type: z.literal("stt.error"),
      sessionId: sttSessionIdSchema,
      failure: relayFailureSchema,
      message: wireText(STT_MESSAGE_MAX_BYTES).optional(),
    })
    .strict(),
  z.object({ type: z.literal("stt.closed"), sessionId: sttSessionIdSchema }).strict(),
] as const;

/** Binary metadata, server to CLI only. */
export const sttAudioMetadataSchema = z
  .object({
    type: z.literal("stt.audio"),
    sessionId: sttSessionIdSchema,
    seq: z.number().int().min(0).max(Number.MAX_SAFE_INTEGER),
  })
  .strict();

/** The `stt.audio` body rule: whole s16 samples, at most one frame's worth. */
export function sttAudioBodyValid(bytes: number): boolean {
  return bytes > 0 && bytes <= STT_AUDIO_FRAME_MAX_BYTES && bytes % 2 === 0;
}
