import { readFileSync, writeFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  encodeRelayBinaryFrame,
  encodeRelayServerControlMessage,
  parseRelayBinaryFrame,
  parseRelayClientControlFrame,
  RELAY_PROTOCOL_VERSIONS,
  type RelayServerControlMessage,
} from "./protocol.js";
import {
  STT_AUDIO_FRAME_MAX_BYTES,
  STT_AUDIO_WINDOW_MAX_BYTES,
  STT_PROMPT_MAX_BYTES,
  sttAudioMetadataSchema,
  sttServerControlSchema,
} from "./stt-protocol.js";

/**
 * The server-to-CLI `stt.*` golden is generated here from the server's own
 * encoder (`UPDATE_STT_GOLDEN=1`, then run biome on the file). The Rust tests
 * (`apps/cli/src/stt_wire_tests.rs`) decode each frame, validate it and
 * re-encode it byte for byte, and refuse every rejected case. The CLI-to-server
 * golden (`stt-events.json`) is generated by Rust and parsed here.
 */
const FIXTURES = new URL("../../../cli/tests/fixtures/relay-current/", import.meta.url);
const FRAMES = new URL("stt-frames.json", FIXTURES);
const EVENTS = new URL("stt-events.json", FIXTURES);

const SESSION = "AAECAwQFBgcICQoLDA0ODw";

type Golden = {
  protocolVersion: string;
  frames: Record<string, string>;
  rejected: Record<string, string>;
  audio: {
    accepted: Record<string, { metadata: string; bodyBytes: number }>;
    rejected: Record<string, { metadata: string; bodyBytes: number }>;
  };
};

function generate(): Golden {
  const open = {
    type: "stt.open",
    sessionId: SESSION,
    endpointSlug: "inst-voxtral-a1b2c3d4e5f6",
    upstreamModel: "mistralai/Voxtral-Mini-4B-Realtime-2602",
    adapter: "vllm",
    config: {},
    maxItemSeconds: 300,
    maxSessionMs: 1_800_000,
    audioWindowBytes: 256 * 1024,
  } as const;
  const encode = (message: RelayServerControlMessage) => encodeRelayServerControlMessage(message);
  const frames = {
    openVllm: encode(open),
    openSegmented: encode({
      ...open,
      adapter: "segmented",
      config: { language: "es-MX", prompt: 'Términos: "WSMP"\nfin' },
      maxItemSeconds: 120,
      maxSessionMs: 1_000,
      audioWindowBytes: STT_AUDIO_WINDOW_MAX_BYTES,
    }),
    openPromptAtLimit: encode({
      ...open,
      adapter: "segmented",
      config: { prompt: "é".repeat(STT_PROMPT_MAX_BYTES / 2) },
      maxItemSeconds: 5,
      audioWindowBytes: STT_AUDIO_FRAME_MAX_BYTES,
    }),
    update: encode({ type: "stt.update", sessionId: SESSION, config: { language: "en" } }),
    updateClears: encode({ type: "stt.update", sessionId: SESSION, config: {} }),
    commit: encode({ type: "stt.commit", sessionId: SESSION, itemSeq: 0 }),
    commitLast: encode({ type: "stt.commit", sessionId: SESSION, itemSeq: 0xffff_ffff }),
    clear: encode({ type: "stt.clear", sessionId: SESSION, itemSeq: 7 }),
    close: encode({ type: "stt.close", sessionId: SESSION, reason: "cancelled" }),
  };
  // Hand-built text: the encoder refuses each, and so must the CLI.
  const raw = (value: Record<string, unknown>) => JSON.stringify(value);
  const rejected = {
    openNonCanonicalSession: raw({ ...open, sessionId: "AAECAwQFBgcICQoLDA0ODx" }),
    openShortSession: raw({ ...open, sessionId: "AAECAwQF" }),
    openReservedSlug: raw({ ...open, endpointSlug: "health" }),
    openEmptyModel: raw({ ...open, upstreamModel: "" }),
    openModel257Bytes: raw({ ...open, upstreamModel: `${"é".repeat(128)}a` }),
    openUnknownAdapter: raw({ ...open, adapter: "openai" }),
    openSegmentedItem121: raw({ ...open, adapter: "segmented", maxItemSeconds: 121 }),
    openItem4: raw({ ...open, maxItemSeconds: 4 }),
    openItem601: raw({ ...open, maxItemSeconds: 601 }),
    openSessionMsTooShort: raw({ ...open, maxSessionMs: 999 }),
    openSessionMsTooLong: raw({ ...open, maxSessionMs: 3_600_001 }),
    openWindowOdd: raw({ ...open, audioWindowBytes: 256 * 1024 + 1 }),
    openWindowTooSmall: raw({ ...open, audioWindowBytes: STT_AUDIO_FRAME_MAX_BYTES - 2 }),
    openWindowTooLarge: raw({ ...open, audioWindowBytes: STT_AUDIO_WINDOW_MAX_BYTES + 2 }),
    openPrompt4097Bytes: raw({ ...open, config: { prompt: `${"é".repeat(2048)}a` } }),
    openLanguageNotToken: raw({ ...open, config: { language: "en US" } }),
    openConfigUnknownKey: raw({ ...open, config: { temperature: 0 } }),
    openConfigArray: raw({ ...open, config: ["en", "prompt"] }),
    openConfigNullLanguage: raw({ ...open, config: { language: null } }),
    updateConfigNullPrompt: raw({
      type: "stt.update",
      sessionId: SESSION,
      config: { prompt: null },
    }),
    updateConfigNumber: raw({ type: "stt.update", sessionId: SESSION, config: 0 }),
    openUnknownKey: raw({ ...open, extra: true }),
    openMissingConfig: raw({ ...open, config: undefined }),
    commitNegative: raw({ type: "stt.commit", sessionId: SESSION, itemSeq: -1 }),
    commitTooLarge: raw({ type: "stt.commit", sessionId: SESSION, itemSeq: 2 ** 32 }),
    commitFraction: raw({ type: "stt.commit", sessionId: SESSION, itemSeq: 1.5 }),
    clearUnknownKey: raw({ type: "stt.clear", sessionId: SESSION, itemSeq: 1, all: true }),
    closeUnknownReason: raw({ type: "stt.close", sessionId: SESSION, reason: "gone" }),
    unknownType: raw({ type: "stt.pause", sessionId: SESSION }),
  };
  const audio = (metadata: Record<string, unknown>, bodyBytes: number) => ({
    metadata: JSON.stringify(metadata),
    bodyBytes,
  });
  const meta = { type: "stt.audio", sessionId: SESSION, seq: 0 };
  return {
    protocolVersion: RELAY_PROTOCOL_VERSIONS[RELAY_PROTOCOL_VERSIONS.length - 1] ?? "",
    frames,
    rejected,
    audio: {
      accepted: {
        twoBytes: audio(meta, 2),
        fullFrame: audio({ ...meta, seq: 41 }, STT_AUDIO_FRAME_MAX_BYTES),
        largestSeq: audio({ ...meta, seq: Number.MAX_SAFE_INTEGER }, 640),
      },
      rejected: {
        empty: audio(meta, 0),
        oddLength: audio(meta, 641),
        overFrame: audio(meta, STT_AUDIO_FRAME_MAX_BYTES + 2),
        negativeSeq: audio({ ...meta, seq: -1 }, 2),
        unsafeSeq: audio({ ...meta, seq: 2 ** 53 }, 2),
        badSession: audio({ ...meta, sessionId: "not-a-session" }, 2),
        unknownKey: audio({ ...meta, final: true }, 2),
      },
    },
  };
}

describe("stt.* server frames golden shared with the CLI decoder", () => {
  const golden = generate();

  it("matches the committed golden", () => {
    const text = `${JSON.stringify(golden, null, 2)}\n`;
    if (process.env.UPDATE_STT_GOLDEN === "1") writeFileSync(FRAMES, text);
    expect(JSON.parse(readFileSync(FRAMES, "utf8"))).toEqual(JSON.parse(text));
  });

  it("refuses to encode every rejected frame", () => {
    for (const [name, wire] of Object.entries(golden.rejected)) {
      const parsed = JSON.parse(wire);
      expect(sttServerControlSchema.safeParse(parsed).success, name).toBe(false);
      expect(() => encodeRelayServerControlMessage(parsed), name).toThrow();
    }
  });

  it("frames audio only within the metadata and body rules", () => {
    for (const [name, { metadata, bodyBytes }] of Object.entries(golden.audio.accepted)) {
      const parsedMetadata = sttAudioMetadataSchema.parse(JSON.parse(metadata));
      const frame = encodeRelayBinaryFrame(parsedMetadata, new Uint8Array(bodyBytes));
      expect(parseRelayBinaryFrame(frame).metadata, name).toEqual(parsedMetadata);
    }
    for (const [name, { metadata, bodyBytes }] of Object.entries(golden.audio.rejected)) {
      let thrown: unknown;
      try {
        encodeRelayBinaryFrame(JSON.parse(metadata), new Uint8Array(bodyBytes));
      } catch (error) {
        thrown = error;
      }
      // The same error type as every other framing refusal, never a ZodError.
      expect((thrown as Error | undefined)?.name, name).toBe("RelayProtocolError");
    }
  });
});

describe("stt.* CLI frames golden generated by the Rust encoder", () => {
  const events: {
    protocolVersion: string;
    frames: Record<string, string>;
    rejected: Record<string, string>;
  } = JSON.parse(readFileSync(EVENTS, "utf8"));

  it("parses every frame the CLI sends exactly", () => {
    expect(events.protocolVersion).toBe(
      RELAY_PROTOCOL_VERSIONS[RELAY_PROTOCOL_VERSIONS.length - 1],
    );
    expect(Object.keys(events.frames).length).toBeGreaterThan(0);
    for (const [name, wire] of Object.entries(events.frames))
      expect(parseRelayClientControlFrame(wire), name).toEqual(JSON.parse(wire));
    const kinds = new Set(
      Object.values(events.frames)
        .map((wire) => JSON.parse(wire) as { type: string; event?: { kind: string } })
        .map((frame) => frame.event?.kind ?? frame.type),
    );
    for (const expected of [
      "stt.opened",
      "stt.audio.ack",
      "stt.error",
      "stt.closed",
      "delta",
      "completed",
      "failed",
      "auto_committed",
    ])
      expect(kinds.has(expected), expected).toBe(true);
  });

  it("refuses every frame the CLI refuses to send", () => {
    expect(Object.keys(events.rejected).length).toBeGreaterThan(0);
    for (const [name, wire] of Object.entries(events.rejected))
      expect(() => parseRelayClientControlFrame(wire), name).toThrow();
  });
});
