import { mkdtemp, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Readable } from "node:stream";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

// service.ts imports the default prisma export only as a fallback; mock the db
// module so importing it never pulls in real env validation. Tests pass their
// own prisma stub explicitly.
vi.mock("@ws-model-proxy/db", () => ({ default: {} }));

const { LocalMediaStore } = await import("./store.js");
const { uploadMedia, MediaQuotaExceededError } = await import("./service.js");
const { MediaTypeNotAllowedError } = await import("./sniff.js");

const PNG = Buffer.from([
  0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66,
]);

function source(buf: Buffer): Readable {
  return Readable.from([buf]);
}

function fakePrisma() {
  return {
    mediaAsset: {
      findFirst: vi.fn(),
      update: vi.fn(),
      create: vi.fn(),
      delete: vi.fn(),
      aggregate: vi.fn().mockResolvedValue({ _sum: { sizeBytes: 0 } }),
    },
  };
}

let root: string;

beforeEach(async () => {
  root = await mkdtemp(join(tmpdir(), "media-svc-"));
});

afterEach(async () => {
  await rm(root, { recursive: true, force: true });
});

describe("uploadMedia", () => {
  it("stores a new asset and commits bytes to the store", async () => {
    const store = new LocalMediaStore(root);
    const prisma = fakePrisma();
    prisma.mediaAsset.findFirst.mockResolvedValue(null);
    // The id is generated by the service (commit-before-create), so the row is
    // written with that id — echo it back like the real DB would.
    prisma.mediaAsset.create.mockImplementation(async ({ data }: { data: { id: string } }) => ({
      id: data.id,
      createdAt: new Date(1000),
    }));

    const result = await uploadMedia({
      source: source(PNG),
      userId: "user-1",
      store,
      ttlHours: 24,
      prisma: prisma as never,
      now: new Date(1000),
    });

    expect(result.deduped).toBe(false);
    expect(result.id).toBeTruthy();
    expect(result.mime).toBe("image/png");
    expect(result.createdAt).toEqual(new Date(1000));
    expect(prisma.mediaAsset.create).toHaveBeenCalledOnce();
    // Bytes were committed under the row's id and are retrievable.
    const object = await store.getStream(result.id);
    expect(object).not.toBeNull();
    expect(object?.sizeBytes).toBe(PNG.length);
  });

  it("commits bytes BEFORE creating the row, and removes the object if create fails", async () => {
    const store = new LocalMediaStore(root);
    const prisma = fakePrisma();
    prisma.mediaAsset.findFirst.mockResolvedValue(null);

    let idAtCreate: string | undefined;
    let bytesPresentAtCreate = false;
    // When create runs, the bytes must already be committed — this proves the
    // commit-before-create ordering that keeps a row from ever existing without
    // its object. Then throw to exercise the failure cleanup.
    prisma.mediaAsset.create.mockImplementation(async ({ data }: { data: { id: string } }) => {
      idAtCreate = data.id;
      bytesPresentAtCreate = (await store.getStream(data.id)) !== null;
      throw new Error("db exploded");
    });

    await expect(
      uploadMedia({
        source: source(PNG),
        userId: "user-1",
        store,
        ttlHours: 24,
        prisma: prisma as never,
        now: new Date(1000),
      }),
    ).rejects.toThrow("db exploded");

    // Ordering: bytes were committed before the create call ran.
    expect(bytesPresentAtCreate).toBe(true);
    // Cleanup: the failed create left no orphan object behind.
    expect(idAtCreate).toBeTruthy();
    expect(await store.getStream(idAtCreate!)).toBeNull();
    // No stray temp file either.
    const tmpEntries = await readdir(join(root, "tmp")).catch(() => [] as string[]);
    expect(tmpEntries).toEqual([]);
  });

  it("rejects a non-allowlisted type and stores nothing", async () => {
    const store = new LocalMediaStore(root);
    const prisma = fakePrisma();

    await expect(
      uploadMedia({
        source: source(Buffer.from("<svg></svg>")),
        userId: "user-1",
        store,
        ttlHours: 24,
        prisma: prisma as never,
      }),
    ).rejects.toBeInstanceOf(MediaTypeNotAllowedError);

    expect(prisma.mediaAsset.create).not.toHaveBeenCalled();
  });

  it("dedups identical bytes for the same user: reuses the asset and refreshes TTL", async () => {
    const store = new LocalMediaStore(root);
    const prisma = fakePrisma();
    // First upload creates the asset.
    prisma.mediaAsset.findFirst.mockResolvedValueOnce(null);
    prisma.mediaAsset.create.mockResolvedValueOnce({ id: "asset-1", createdAt: new Date(1000) });
    await uploadMedia({
      source: source(PNG),
      userId: "user-1",
      store,
      ttlHours: 24,
      prisma: prisma as never,
      now: new Date(1000),
    });

    // Second identical upload finds the existing unexpired asset.
    const originalCreatedAt = new Date(1000);
    prisma.mediaAsset.findFirst.mockResolvedValueOnce({
      id: "asset-1",
      mime: "image/png",
      sizeBytes: PNG.length,
      createdAt: originalCreatedAt,
    });
    const now = new Date(2000);
    const result = await uploadMedia({
      source: source(PNG),
      userId: "user-1",
      store,
      ttlHours: 24,
      prisma: prisma as never,
      now,
    });

    expect(result.deduped).toBe(true);
    expect(result.id).toBe("asset-1");
    // Dedup returns the original asset's createdAt, not `now`.
    expect(result.createdAt).toEqual(originalCreatedAt);
    // Only one create total; the dedup path refreshes expiresAt instead.
    expect(prisma.mediaAsset.create).toHaveBeenCalledOnce();
    expect(prisma.mediaAsset.update).toHaveBeenCalledWith({
      where: { id: "asset-1" },
      data: { expiresAt: new Date(now.getTime() + 24 * 60 * 60 * 1000) },
    });
  });

  it("rejects an upload that would exceed the per-user quota and stores nothing", async () => {
    const store = new LocalMediaStore(root);
    const prisma = fakePrisma();
    prisma.mediaAsset.findFirst.mockResolvedValue(null); // no dedup hit
    // User already holds 10 bytes; the quota is 20; this PNG is 14 → 24 > 20.
    prisma.mediaAsset.aggregate.mockResolvedValue({ _sum: { sizeBytes: 10 } });

    await expect(
      uploadMedia({
        source: source(PNG),
        userId: "user-1",
        store,
        ttlHours: 24,
        maxBytesPerUser: 20,
        prisma: prisma as never,
        now: new Date(1000),
      }),
    ).rejects.toBeInstanceOf(MediaQuotaExceededError);

    // No row created, and the staged temp file was discarded (no leak).
    expect(prisma.mediaAsset.create).not.toHaveBeenCalled();
    const tmpEntries = await readdir(join(root, "tmp")).catch(() => [] as string[]);
    expect(tmpEntries).toEqual([]);
  });

  it("passes when existing + new bytes land EXACTLY at the quota", async () => {
    const store = new LocalMediaStore(root);
    const prisma = fakePrisma();
    prisma.mediaAsset.findFirst.mockResolvedValue(null);
    // 10 existing + 14 (PNG) == 24 quota → allowed (only strictly-over rejects).
    prisma.mediaAsset.aggregate.mockResolvedValue({ _sum: { sizeBytes: 10 } });
    prisma.mediaAsset.create.mockImplementation(async ({ data }: { data: { id: string } }) => ({
      id: data.id,
      createdAt: new Date(1000),
    }));

    const result = await uploadMedia({
      source: source(PNG),
      userId: "user-1",
      store,
      ttlHours: 24,
      maxBytesPerUser: 10 + PNG.length,
      prisma: prisma as never,
      now: new Date(1000),
    });

    expect(result.deduped).toBe(false);
    expect(prisma.mediaAsset.create).toHaveBeenCalledOnce();
  });

  it("exempts a dedup hit from the quota (adds no new bytes)", async () => {
    const store = new LocalMediaStore(root);
    const prisma = fakePrisma();
    // Identical unexpired asset already exists → dedup path returns early.
    prisma.mediaAsset.findFirst.mockResolvedValue({
      id: "asset-dup",
      mime: "image/png",
      sizeBytes: PNG.length,
      createdAt: new Date(500),
    });

    const result = await uploadMedia({
      source: source(PNG),
      userId: "user-1",
      store,
      ttlHours: 24,
      // Quota of 1 byte would reject any real new upload; dedup must skip it.
      maxBytesPerUser: 1,
      prisma: prisma as never,
      now: new Date(1000),
    });

    expect(result.deduped).toBe(true);
    // The quota aggregate was never consulted on the dedup path.
    expect(prisma.mediaAsset.aggregate).not.toHaveBeenCalled();
    expect(prisma.mediaAsset.create).not.toHaveBeenCalled();
  });
});
