//! Relay 2.11 live speech-to-text frames (`stt.*`), the mirror of
//! `apps/server/src/relay/stt-protocol.ts`.
//!
//! The server opens a session on one endpoint that advertises
//! `audio.transcriptions.realtime`, streams raw PCM (`stt.audio` binary
//! frames: s16le, 24 kHz mono, even length, at most 32 KiB) and receives
//! normalized events. Engine and OpenAI event JSON never cross the relay.
//!
//! Shared goldens in `tests/fixtures/relay-current/`:
//! `stt-frames.json` (server to CLI, generated by the server tests) and
//! `stt-events.json` (CLI to server, generated here with `WSMP_UPDATE_GOLDEN`).
//! Text limits are UTF-8 bytes on both sides.

use anyhow::{Result, bail, ensure};
use serde::{Deserialize, Serialize};

use crate::config::RealtimeAdapter;
use crate::protocol::{ClientControlMessage, RelayFailure};

pub const STT_AUDIO_FRAME_MAX_BYTES: usize = 32 * 1024;
pub const STT_AUDIO_WINDOW_MIN_BYTES: u32 = STT_AUDIO_FRAME_MAX_BYTES as u32;
pub const STT_AUDIO_WINDOW_MAX_BYTES: u32 = 1024 * 1024;
pub const STT_MAX_SESSION_MS_MIN: u64 = 1_000;
pub const STT_MAX_SESSION_MS_MAX: u64 = 60 * 60 * 1_000;
pub const STT_MODEL_MAX_BYTES: usize = 256;
pub const STT_PROMPT_MAX_BYTES: usize = 4096;
/// The CLI splits longer delta text.
pub const STT_DELTA_TEXT_MAX_BYTES: usize = 16 * 1024;
/// A longer transcript fails the item (`transcript_too_large`).
pub const STT_COMPLETED_TEXT_MAX_BYTES: usize = 48 * 1024;
pub const STT_MESSAGE_MAX_BYTES: usize = 512;
pub const STT_TOKEN_COUNT_MAX: u64 = 1_000_000_000_000;
const MAX_ITEM_SECONDS_MIN: u32 = 5;
const MAX_ITEM_SECONDS_MAX: u32 = 600;
const SEGMENTED_MAX_ITEM_SECONDS_MAX: u32 = 120;
/// JavaScript's `Number.MAX_SAFE_INTEGER`: the server cannot send a larger `seq`.
const SAFE_INTEGER_MAX: u64 = (1 << 53) - 1;

/// Per-item options; the vLLM adapter has neither.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SttConfig {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt: Option<String>,
}

impl SttConfig {
    fn validate(&self) -> Result<()> {
        if let Some(language) = &self.language {
            ensure!(
                (1..=64).contains(&language.len())
                    && language
                        .bytes()
                        .all(|b| b.is_ascii_alphanumeric() || b"_.+/-".contains(&b)),
                "stt config language is not a token"
            );
        }
        if let Some(prompt) = &self.prompt {
            ensure!(
                prompt.len() <= STT_PROMPT_MAX_BYTES,
                "stt config prompt exceeds {STT_PROMPT_MAX_BYTES} bytes"
            );
        }
        Ok(())
    }
}

/// Server to CLI JSON control frames.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all_fields = "camelCase", deny_unknown_fields)]
pub enum SttServerMessage {
    #[serde(rename = "stt.open")]
    Open {
        session_id: String,
        endpoint_slug: String,
        upstream_model: String,
        adapter: RealtimeAdapter,
        config: SttConfig,
        max_item_seconds: u32,
        max_session_ms: u64,
        audio_window_bytes: u32,
    },
    /// Applies to the next item.
    #[serde(rename = "stt.update")]
    Update {
        session_id: String,
        config: SttConfig,
    },
    #[serde(rename = "stt.commit")]
    Commit { session_id: String, item_seq: u32 },
    #[serde(rename = "stt.clear")]
    Clear { session_id: String, item_seq: u32 },
    #[serde(rename = "stt.close")]
    Close {
        session_id: String,
        reason: RelayFailure,
    },
}

impl SttServerMessage {
    pub fn session_id(&self) -> &str {
        match self {
            Self::Open { session_id, .. }
            | Self::Update { session_id, .. }
            | Self::Commit { session_id, .. }
            | Self::Clear { session_id, .. }
            | Self::Close { session_id, .. } => session_id,
        }
    }

    /// The bounds `sttServerControlSchema` holds beyond the shape serde checks.
    pub fn validate(&self) -> Result<()> {
        ensure!(
            is_session_id(self.session_id()),
            "stt session id is not 16 bytes of canonical base64url"
        );
        match self {
            Self::Open {
                endpoint_slug,
                upstream_model,
                adapter,
                config,
                max_item_seconds,
                max_session_ms,
                audio_window_bytes,
                ..
            } => {
                crate::slug::validate_slug(endpoint_slug)?;
                ensure!(
                    (1..=STT_MODEL_MAX_BYTES).contains(&upstream_model.len())
                        && !upstream_model.contains('\0'),
                    "stt.open upstream model is out of bounds"
                );
                config.validate()?;
                let item_max = match adapter {
                    RealtimeAdapter::Segmented => SEGMENTED_MAX_ITEM_SECONDS_MAX,
                    RealtimeAdapter::Vllm => MAX_ITEM_SECONDS_MAX,
                };
                ensure!(
                    (MAX_ITEM_SECONDS_MIN..=item_max).contains(max_item_seconds),
                    "stt.open maxItemSeconds is out of bounds"
                );
                ensure!(
                    (STT_MAX_SESSION_MS_MIN..=STT_MAX_SESSION_MS_MAX).contains(max_session_ms),
                    "stt.open maxSessionMs is out of bounds"
                );
                ensure!(
                    (STT_AUDIO_WINDOW_MIN_BYTES..=STT_AUDIO_WINDOW_MAX_BYTES)
                        .contains(audio_window_bytes)
                        && audio_window_bytes.is_multiple_of(2),
                    "stt.open audioWindowBytes is out of bounds"
                );
                Ok(())
            }
            Self::Update { config, .. } => config.validate(),
            Self::Commit { .. } | Self::Clear { .. } | Self::Close { .. } => Ok(()),
        }
    }
}

/// Token usage an engine reported for one item.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SttEngineUsage {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_tokens: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_tokens: Option<u64>,
}

/// A normalized transcription event (`stt.event`), CLI to server.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    tag = "kind",
    rename_all = "snake_case",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum SttEvent {
    Delta {
        item_seq: u32,
        text: String,
    },
    Completed {
        item_seq: u32,
        text: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        engine_usage: Option<SttEngineUsage>,
    },
    Failed {
        item_seq: u32,
        code: String,
        message: String,
    },
    /// The `maxItemSeconds` valve ended the open item.
    AutoCommitted {
        item_seq: u32,
    },
}

impl SttEvent {
    fn validate(&self) -> Result<()> {
        match self {
            Self::Delta { text, .. } => ensure!(
                text.len() <= STT_DELTA_TEXT_MAX_BYTES,
                "stt delta exceeds {STT_DELTA_TEXT_MAX_BYTES} bytes"
            ),
            Self::Completed {
                text, engine_usage, ..
            } => {
                ensure!(
                    text.len() <= STT_COMPLETED_TEXT_MAX_BYTES,
                    "stt transcript exceeds {STT_COMPLETED_TEXT_MAX_BYTES} bytes"
                );
                if let Some(usage) = engine_usage {
                    ensure!(
                        [usage.input_tokens, usage.output_tokens]
                            .into_iter()
                            .flatten()
                            .all(|tokens| tokens <= STT_TOKEN_COUNT_MAX),
                        "stt engine usage is out of bounds"
                    );
                }
            }
            Self::Failed { code, message, .. } => {
                ensure!(
                    (1..=64).contains(&code.len())
                        && code
                            .bytes()
                            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_'),
                    "stt failure code is not a token"
                );
                ensure!(
                    message.len() <= STT_MESSAGE_MAX_BYTES,
                    "stt failure message exceeds {STT_MESSAGE_MAX_BYTES} bytes"
                );
            }
            Self::AutoCommitted { .. } => {}
        }
        Ok(())
    }
}

/// The bounds `sttClientControlSchemas` holds for a CLI to server `stt.*`
/// frame; `Ok` for every other frame. `encode_control` refuses a frame that
/// fails, so nothing outside the server's contract is ever sent.
pub fn validate_client_message(message: &ClientControlMessage) -> Result<()> {
    let session_id = match message {
        ClientControlMessage::SttOpened { session_id }
        | ClientControlMessage::SttClosed { session_id } => session_id,
        ClientControlMessage::SttAudioAck { session_id, bytes } => {
            ensure!(
                (1..=STT_AUDIO_WINDOW_MAX_BYTES).contains(bytes),
                "stt.audio.ack bytes are out of bounds"
            );
            session_id
        }
        ClientControlMessage::SttEvent { session_id, event } => {
            event.validate()?;
            session_id
        }
        ClientControlMessage::SttError {
            session_id,
            message,
            ..
        } => {
            if message
                .as_ref()
                .is_some_and(|message| message.len() > STT_MESSAGE_MAX_BYTES)
            {
                bail!("stt.error message exceeds {STT_MESSAGE_MAX_BYTES} bytes");
            }
            session_id
        }
        _ => return Ok(()),
    };
    ensure!(
        is_session_id(session_id),
        "stt session id is not 16 bytes of canonical base64url"
    );
    Ok(())
}

/// The `stt.audio` binary frame rule (metadata and body).
pub fn validate_audio_frame(session_id: &str, seq: u64, body_len: usize) -> Result<()> {
    ensure!(
        is_session_id(session_id),
        "stt session id is not 16 bytes of canonical base64url"
    );
    ensure!(seq <= SAFE_INTEGER_MAX, "stt.audio seq is out of bounds");
    ensure!(
        body_len > 0 && body_len <= STT_AUDIO_FRAME_MAX_BYTES && body_len.is_multiple_of(2),
        "stt.audio carries 1 to {STT_AUDIO_FRAME_MAX_BYTES} bytes of whole samples"
    );
    Ok(())
}

/// 16 raw bytes as canonical unpadded base64url (22 characters).
pub fn is_session_id(value: &str) -> bool {
    value.len() == 22
        && base64::Engine::decode(&base64::engine::general_purpose::URL_SAFE_NO_PAD, value)
            .is_ok_and(|bytes| bytes.len() == 16)
}

#[cfg(test)]
#[path = "stt_wire_tests.rs"]
mod tests;
